### ISSUE TITLE
Using wcs layer as raster does not work

### ISSUE THREAD

**Issue by assefay** [inasafe/inasafe#1333]
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1471, in accept
    self.run()
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1538, in run
    self.setup_calculator()
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 1259, in setup_calculator
    hazard_layer, exposure_layer = self.optimal_clip()
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/widgets/dock.py", line 2144, in optimal_clip
    hard_clip_flag=self.clip_hard)
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/utilities/clipper.py", line 124, in clip_layer
    extra_keywords=extra_keywords)
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/utilities/clipper.py", line 457, in _clip_raster_layer
    verify(os.path.isfile(keywords_path), message)
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe_qgis/safe_interface.py", line 138, in verify
    verify_util(statement, message)
  File "/home/yassefa/.qgis2/python/plugins/inasafe/safe/common/utilities.py", line 72, in verify
    raise VerificationError(message)
VerificationError: Input file to be clipped "cache=AlwaysCache&crs=EPSG:4326&format=GeoTIFF&identifier=geonode:flood_hkv_current_jakarta&password=opendri&url=http://54.167.92.192/geoserver/wcs&username=opendri" does not have the expected keywords file cache=AlwaysCache&crs=EPSG:4326&format=GeoTIFF&identifier=geonode:flood_hkv_current_jakarta&password=opendri&url=http://54.167.92.192/geoserver/wcs&username=opendri.keywords

**Comment by akbargumbira** [comment]
Hi, I just realised that this is for 3.0. Anyone has a published WCS layer so that I can try this?

**Comment by NyakudyaA** [comment]
WCS layers now work properly. Keywords are properly saved in the database. 
![wcs](https://cloud.githubusercontent.com/assets/2510900/22424601/e3e89466-e6ff-11e6-9f8a-b79036a51fe6.png)

**Comment by ismailsunni** [comment]
Amazing I must say :D, I never check again the keyword for remote layer, and it's still working :)
