### ISSUE TITLE
Postprocessing fails with QGIS-master (will be 2.10)

### ISSUE THREAD

**Issue by wonder-sk** [inasafe/inasafe#2010]
When running some (all?) analyses (tested with flooding raster/roads), the postprocessing fails:

```
Traceback (most recent call last):
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 936, in run_aggregator
    self.run_post_processor()
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 950, in run_post_processor
    self.postprocessor_manager.run()
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/impact_statistics/postprocessor_manager.py", line 482, in run
    value.process()
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/postprocessors/building_type_postprocessor.py", line 119, in process
    self._calculate_total()
  File "/home/martin/.qgis2/python/plugins/inasafe/safe/postprocessors/building_type_postprocessor.py", line 143, in _calculate_total
    result = int(round(result))
TypeError: a float is required
```

This is because `result` is actualy a `QPyNullVariant` object instead of a real number. Handling `TypeError` in `_calculate_total()` method could be a workaround, but it's better to investigate why it is null.

Running the same code with QGIS 2.6 works without issues.

**Comment by Gustry** [comment]
This is not relevant anymore with inasafe v4.
