### ISSUE TITLE
We should gracefully handle incorrect item types for composer layouts

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2033]
If I create a composer item with a token id - e.g. `impact-report` and the item type differs (e.g. we used an html item instead of a text item), we get an error at run time when trying to open the composer, and pdf generator fails silently.

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/home/kurnia/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 1765, in print_map
    self.open_map_in_composer(impact_report)
  File "/home/kurnia/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 1848, in open_map_in_composer
    impact_report.draw_composition()
  File "/home/kurnia/.qgis2/python/plugins/inasafe-dev/safe/report/impact_report.py", line 380, in draw_composition
    table.setText(text)
AttributeError: 'QgsComposerFrame' object has no attribute 'setText'
```

We should trap for and raise a nice error message if this happens.

**Comment by timlinux** [comment]
@lucernae can you take this ticket please

**Comment by timlinux** [comment]
@myarjunar please check & close
