### ISSUE TITLE
Qgis does not load inasafe

### ISSUE THREAD

**Issue by Samweli** [inasafe/inasafe#2147]
Qgis does not load inasafe after unexpected disconnection from the remote debugger

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/twesa/.qgis2/python/plugins/inasafe/__init__.py", line 88, in classFactory
    pydevd.settrace('localhost', port=5678, stdoutToServer=True, stderrToServer=True)
  File "/usr/local/lib/python2.7/dist-packages/pycharm-debug.egg/pydevd.py", line 1949, in settrace
    patch_multiprocessing,
  File "/usr/local/lib/python2.7/dist-packages/pycharm-debug.egg/pydevd.py", line 1988, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/usr/local/lib/python2.7/dist-packages/pycharm-debug.egg/pydevd.py", line 459, in connect
    s = StartClient(host, port)
  File "/usr/local/lib/python2.7/dist-packages/pycharm-debug.egg/pydevd_comm.py", line 489, in StartClient
    sys.exit(1) #TODO: is it safe?
SystemExit: 1

**Comment by ismailsunni** [comment]
Hi @Samweli 
If you use remote debugger, you need to run the remote debugger in PyCharm. Otherwise, it will give you error.
Please remove the additional line `pydevd.settrace('localhost', port=5678, stdoutToServer=True, stderrToServer=True)` if you want to use InaSAFE not in remote debug mode.

Thanks.

**Comment by ismailsunni** [comment]
I think we can close this since it should be solved by removing that pydev line for remote debugging.
I always find this error if I forgot to remove the lines, and do not run remote debugger.
