### ISSUE TITLE
Problem running inasafe in ubuntu 12.04

### ISSUE THREAD

**Issue by Samweli** [inasafe/inasafe#2148]
Problem running inasafe in ubuntu 12.04, inasafe cant create a file in /tmp

```
Traceback (most recent call last):
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1192, in accept
    self.analysis.run_analysis()
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 957, in run_analysis
    self.setup_impact_calculator()
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 833, in setup_impact_calculator
    self.aggregator.set_layers(hazard_layer, exposure_layer)
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 442, in set_layers
    self.safe_layer = safe_read_layer(self.layer.source())
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/storage/vector.py", line 163, in __init__
    self.read_from_file(data)
  File "/home/twesa/.qgis2/python/plugins/inasafe/safe/storage/vector.py", line 446, in read_from_file
    fid = ogr.Open(filename)
  File "/usr/lib/python2.7/dist-packages/osgeo/ogr.py", line 4048, in Open
    return _ogr.Open(*args, **kwargs)
TypeError: in method 'Open', argument 1 of type 'char const *'
```

**Comment by ismailsunni** [comment]
Hi @Samweli 
Can you tell us what did you do when get that error? If possible, can you share the data that you use?
Thanks

**Comment by Gustry** [comment]
We don't have the storage package anymore in inasafe v4, I will close this ticket.
