### ISSUE TITLE
Fast tests fail when inasafe-data is not present

### ISSUE THREAD

**Issue by ingenieroariel** [inasafe/inasafe#217]
We should copy small versions to the unit data directory that let the fast tests run. Here is the full log of the 34 tests that are failing because of missing datasets.

```

geonode)ubuntu@domU-12-31-39-04-0E-F0:~$ python
Python 2.7.3 (default, Apr 20 2012, 22:39:59) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import safe
>>> safe.test()
Running unit tests for safe
safe version 0.5.5
NumPy version 1.6.1
NumPy is installed in /usr/lib/python2.7/dist-packages/numpy
Python version 2.7.3 (default, Apr 20 2012, 22:39:59) [GCC 4.6.3]
nose version 1.1.2
.......................................................ERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/itb_test_mmi.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/lembang_mmi_hazmap.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

E.ERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/hazard/Flood_Current_Depth_Jakarta_geographic.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

E.ERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/lembang_mmi_hazmap.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/tsunami_max_inundation_depth_utm56s.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/hazard/maumere_aos_depth_20m_land_wgs84.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/hazard/Flood_Current_Depth_Jakarta_geographic.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

ESS..SEERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Ashload_Gede_VEI4_geographic.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/tsunami_max_inundation_depth_4326.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

EE..........FE.EERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/bad_ascii_format.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

FERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/population_padang_1.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

E...E...ERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

EF.E.EE.FERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/grid_without_projection.asc' does not exist in the file system,
and is not recognised as a supported dataset name.

EEEERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

E.ERROR 4: `/var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

EEEE.E
======================================================================
ERROR: Fatalities from ground shaking can be computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 187, in test_ITB_earthquake_fatality_estimation
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/itb_test_mmi.asc

======================================================================
ERROR: Lembang building damage from ground shaking works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 514, in test_earthquake_damage_schools
    H = read_layer(haz_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/lembang_mmi_hazmap.asc

======================================================================
ERROR: Fatalities from ground shaking can be computed correctly 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 122, in test_earthquake_fatality_estimation_allen
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif

======================================================================
ERROR: Fatalities from ground shaking can be computed correctly 2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 278, in test_earthquake_fatality_estimation_ghasemi
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif

======================================================================
ERROR: Earthquake impact on women example works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 344, in test_earthquake_impact_on_women_example
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif

======================================================================
ERROR: Jakarta flood impact on roads calculated correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 2192, in test_flood_on_roads
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/hazard/Flood_Current_Depth_Jakarta_geographic.asc

======================================================================
ERROR: Interpolation using Lembang data set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 1050, in test_interpolation_lembang
    hazard_raster = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/lembang_mmi_hazmap.asc

======================================================================
ERROR: Interpolation using tsunami data set works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 1121, in test_interpolation_tsunami
    hazard_raster = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/tsunami_max_inundation_depth_utm56s.tif

======================================================================
ERROR: Interpolation using tsunami data set from Maumere
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 1160, in test_interpolation_tsunami_maumere
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/hazard/maumere_aos_depth_20m_land_wgs84.asc

======================================================================
ERROR: Layers without keywords raise exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 1991, in test_layer_integrity_raises_exception
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/hazard/Flood_Current_Depth_Jakarta_geographic.asc

======================================================================
ERROR: Clipping using real polygon and point data from Maumere
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 1236, in test_polygon_clipping
    fid = open(polygon_filename)
IOError: [Errno 2] No such file or directory: '/var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_poly.txt'

======================================================================
ERROR: Hypothetical tephra load scenario can be computed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 827, in test_tephra_load_impact
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Ashload_Gede_VEI4_geographic.asc

======================================================================
ERROR: Building loss from tsunami use case works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/engine/test_engine.py", line 714, in test_tsunami_loss_use_case
    H = read_layer(hazard_filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/tsunami_max_inundation_depth_4326.tif

======================================================================
ERROR: Failure: ImportError (No module named storage.core)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/impact_functions/test_mappings.py", line 8, in <module>
    from storage.core import read_layer
ImportError: No module named storage.core

======================================================================
ERROR: Analysis of vector data - get top N of an attribute
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 228, in test_analysis_of_vector_data_top_N
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_buildings.shp

======================================================================
ERROR: Different attribute types are handled correctly in vector data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 410, in test_attribute_types
    V = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_buildings.shp

======================================================================
ERROR: Linear and quantile bins are correct
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1001, in test_bins
    R = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/population_padang_1.asc

======================================================================
ERROR: Centroid point data can be derived from polygon data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 564, in test_centroids_from_polygon_data
    p_layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/kecamatan_jakarta_osm.shp

======================================================================
ERROR: Bounding box is correctly extracted from file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1126, in test_get_bounding_box
    bbox = get_bounding_box(os.path.join(TESTDATA, filename))
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 93, in get_bounding_box
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif

======================================================================
ERROR: Keywords can be written and read
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1233, in test_keywords_file
    V = read_layer('%s/test_buildings.shp' % TESTDATA)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_buildings.shp

======================================================================
ERROR: Vector and Raster instances have a similar API
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1159, in test_layer_API
    L = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_buildings.shp

======================================================================
ERROR: Points along line are computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1676, in test_line_to_points
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/indonesia_highway_sample.shp

======================================================================
ERROR: Raster layers with no projection causes Exception to be raised
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 846, in test_no_projection
    read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/grid_without_projection.asc

======================================================================
ERROR: Polygon areas are computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1560, in test_polygon_area
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_polygon.shp

======================================================================
ERROR: Polygon centroids are computed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1609, in test_polygon_centroids
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_polygon.shp

======================================================================
ERROR: Raster extrema (including NAN's) are correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 968, in test_raster_extrema
    R = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif

======================================================================
ERROR: Rasters can be read and written correctly in different formats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 754, in test_reading_and_writing_of_real_rasters
    R1 = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 26, in read_layer
    return Raster(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 76, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/raster.py", line 152, in read_from_file
    raise Exception(msg)
Exception: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/Earthquake_Ground_Shaking_clip.tif

======================================================================
ERROR: Vector line data can be read and written correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1737, in test_reading_and_writing_of_vector_line_data
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/indonesia_highway_sample.shp

======================================================================
ERROR: Vector polygon data can be read and written correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 463, in test_reading_and_writing_of_vector_polygon_data
    layer = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/kecamatan_jakarta_osm.shp

======================================================================
ERROR: Consistency of vector class for point data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 269, in test_vector_class
    V = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_buildings.shp

======================================================================
ERROR: Vector extremum calculation works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 920, in test_vector_extrema
    L = read_layer(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/core.py", line 28, in read_layer
    return Vector(filename)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 92, in __init__
    self.read_from_file(data)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/vector.py", line 299, in read_from_file
    raise IOError(msg)
IOError: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/test/test_buildings.shp

======================================================================
FAIL: Impact functions are filtered correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/impact_functions/test_real_impact_functions.py", line 31, in test_filtering_of_impact_functions
    assert 'Padang Earthquake Building Damage Function' in P, msg
AssertionError: Available impact functions are: ['F1', 'F2', 'F3', 'Earthquake Building Damage Function', 'Basic Function', 'Syntax Error Function', 'Empirical Fatality Function', 'Earthquake Guidelines Function', 'Tsunami Building Loss Function', 'Tephra Building Impact Function', 'HKVtest', 'Earthquake Fatality Function', 'Flood Road Impact Function']

======================================================================
FAIL: ASC raster files with bad data causes good error message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 870, in test_bad_ascii_data
    assert 'exists' in str(e), msg
AssertionError: Unexpected error message for corrupt asc file: Could not find file /var/lib/geonode/local/lib/python2.7/inasafe_data/test/bad_ascii_format.asc

======================================================================
FAIL: Test to see if internationalisation is working correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1857, in test_i18n
    assert indoout1 == indoexpected1, msg
AssertionError: Expected Hi, got Hello!

======================================================================
FAIL: Multipart polygons raise exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/geonode/local/lib/python2.7/site-packages/safe/storage/test_io.py", line 1869, in test_multipart_polygon_raises_exception
    assert 'convert multipart' in str(e), msg
AssertionError: Wrong error message: Could not open /var/lib/geonode/local/lib/python2.7/inasafe_data/boundaries/rw_jakarta.shp

----------------------------------------------------------------------
Ran 119 tests in 3.709s

FAILED (SKIP=3, errors=31, failures=4)
<nose.result.TextTestResult run=119 errors=31 failures=4>
```

**Comment by timlinux** [comment]
@ingeneiroariel I am going to close this ticket as old. We have have a plan to create small test datasets and deprecate the need for inasafe_data completely for unit tests.

**Comment by ismailsunni** [comment]
May be this issue can be a small step for using small data test for running make test faster.

**Comment by ismailsunni** [comment]
Covered in #1448 closing this.
