### ISSUE TITLE
Shakemap Converter: Failed to parse grid file

### ISSUE THREAD

**Issue by roscoeKartoza** [inasafe/inasafe#2319]
# Problem
I'm getting 'GridXmlParseError: Failed to parse grid file.'

# Data
http://earthquake.usgs.gov/earthquakes/shakemap/global/shake/c000luwe/download/grid.xml

# Traceback
```
Traceback (most recent call last):
  File "C:/Users/Roscoe/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shakemap_converter_dialog.py", line 223, in accept
    algorithm_filename_flag=True)
  File "C:/Users/Roscoe/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 912, in convert_mmi_data
    algorithm_filename_flag=algorithm_filename_flag)
  File "C:/Users/Roscoe/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 141, in __init__
    self.parse_grid_xml()
  File "C:/Users/Roscoe/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 298, in parse_grid_xml
    'Failed to parse grid file.\n%s\n%s' % (e.__class__, str(e)))
GridXmlParseError: Failed to parse grid file.

'Asia/Jakarta'
```
# Environment
Windows 8.1 (64bit)
QGIS 2.8.3
Inasafe 3.2.0

**Comment by timlinux** [comment]
@lucernae can you check this out please?

**Comment by lucernae** [comment]
I'm using the same grid.xml and can't replicate it.

# Environment

Linux 15. (64bit)
QGIS 2.10
Inasafe 3.2.0

**Comment by lucernae** [comment]
Closing this as we can't replicate this now.

**Comment by lucernae** [comment]
Totally forgot, maybe this is platform specific as reported by @ivanbusthomi . Not safe to close this now.
@ivanbusthomi could you please post your environment here?

**Comment by ivanbusthomi** [comment]
@lucernae 
Tried this in Ubuntu , and it does not give any error

# Environment
* OS : Ubuntu 16.04 64bit
* QGIS : 2.14.3
* InaSAFE : 3.4.0

___

But when I tried running in Windows, I get this error:
```
GridXmlParseError: Failed to parse grid file. 'Asia/Jakarta' 
Traceback (most recent call last):
  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shakemap_converter_dialog.py", line 184, in accept
    algorithm_filename_flag=True)
  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 931, in convert_mmi_data
    algorithm_filename_flag=algorithm_filename_flag)
  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 143, in __init__
    self.parse_grid_xml()
  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 300, in parse_grid_xml
    'Failed to parse grid file.\n%s\n%s' % (e.__class__, str(e)))
GridXmlParseError: Failed to parse grid file.

'Asia/Jakarta'
```

# Environment
* OS : Windows 7 64 bit
* QGIS : 2.14.1
* InaSAFE : 3.4.0

**Comment by Charlotte-Morgan** [comment]
see #2922
 ## environment ##
OS : Windows 7 64 bit
QGIS : 2.14.3
InaSAFE : 3.4.0

**Comment by Charlotte-Morgan** [comment]
## problem
i got the following error when running the shakemap converter
```
An error has occurred while executing Python code: 

GridXmlParseError: Failed to parse grid file. 'Asia/Jakarta' 
Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shakemap_converter_dialog.py", line 184, in accept
    algorithm_filename_flag=True)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 931, in convert_mmi_data
    algorithm_filename_flag=algorithm_filename_flag)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 143, in __init__
    self.parse_grid_xml()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 300, in parse_grid_xml
    'Failed to parse grid file.\n%s\n%s' % (e.__class__, str(e)))
GridXmlParseError: Failed to parse grid file.

'Asia/Jakarta'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.3-Essen Essen, cf2ebb8 

Python Path:
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISES~1/apps/qgis/./python
C:/Users/AIFDR_ADMIN/.qgis2/python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins
C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg
C:\Program Files (x86)\ArcGIS\Desktop10.2\bin
C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy
C:\Program Files (x86)\ArcGIS\Desktop10.2\ArcToolbox
C:\PROGRA~1\QGISES~1\bin\python27.zip
C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
C:\PROGRA~1\QGISES~1\apps\Python27\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISES~1\bin
C:\PROGRA~1\QGISES~1\apps\Python27
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/AIFDR_ADMIN/.qgis2//python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
```
## data
*.xml file downloaded from Realtime earthquake for event 20160608021514

## cc
@lucernae @timlinux @ivanbusthomi

**Comment by Charlotte-Morgan** [comment]
hi @lucernae  - I have put your name on this :)
Great if you can take another look. I wanted to recommend a workflow to some new users but not if its not working.  thanks

**Comment by lucernae** [comment]
Yeah, hard to debug it in Windows. 
At least, we can be sure now it is windows only problem.
I'm still following it up in my windows environment.

**Comment by NyakudyaA** [comment]
@lucernae  I can replicate this on Ubuntu 16.04.

Data: `http://earthquake.usgs.gov/earthquakes/shakemap/atlas/shake/200712081955/download/grid.xml`
OS:        Ubuntu 16.04
Inasafe:    3.05
QGIS:      2.14.3

`
An error has occurred while executing Python code: 
GridXmlParseError: Failed to parse grid file. list index out of range 
Traceback (most recent call last):
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/tools/shake_grid/shakemap_converter_dialog.py", line 184, in accept
    algorithm_filename_flag=True)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/tools/shake_grid/shake_grid.py", line 906, in convert_mmi_data
    algorithm_filename_flag=algorithm_filename_flag)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/tools/shake_grid/shake_grid.py", line 143, in __init__
    self.parse_grid_xml()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/tools/shake_grid/shake_grid.py", line 300, in parse_grid_xml
    'Failed to parse grid file.\n%s\n%s' % (e.__class__, str(e)))
GridXmlParseError: Failed to parse grid file.
list index out of range
Python version: 2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413] 
QGIS version: 2.14.3-Essen Essen, exported `

**Comment by lucernae** [comment]
@NyakudyaA Can you checkout my branch in https://github.com/inasafe/inasafe/pull/3030 and check the issue on Ubuntu and Windows?

**Comment by ivanbusthomi** [comment]
@lucernae LGTM in Ubuntu 16.04 using both USGS data and realtime data

**Comment by felix-yew** [comment]
@lucernae LGTM in Windows 7-64bit :+1:

**Comment by lucernae** [comment]
Finally, closing this and move out to #3145
