### ISSUE TITLE
BUG : Can Not Use the Wizard

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2515]
# Problem
An error has occured when use both of Keyword Wizard and Impact Function Centric Wizard

```
An error has occured while executing Python code: 

ImportError: No module named qgsdatetimeedit 
Traceback (most recent call last):
  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\plugin.py", line 617, in show_keywords_wizard
    from safe.gui.tools.wizard_dialog import WizardDialog
  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 130, in 
    FORM_CLASS = get_ui_class('wizard_dialog_base.ui')
  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\utilities\resources.py", line 97, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
  File "C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 1925, in 
  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named qgsdatetimeedit


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.12.1-Lyon Lyon, 16760fd 

Python Path:
C:/Users/kurnia/.qgis2/python/plugins\processing
C:/PROGRA~1/QGISLY~1/apps/qgis/./python
C:/Users/kurnia/.qgis2/python
C:/Users/kurnia/.qgis2/python/plugins
C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGISLY~1\bin\python27.zip
C:\PROGRA~1\QGISLY~1\apps\Python27\DLLs
C:\PROGRA~1\QGISLY~1\apps\Python27\lib
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\plat-win
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGISLY~1\bin
C:\PROGRA~1\QGISLY~1\apps\Python27
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/kurnia/.qgis2//python
C:/Users/kurnia/.qgis2/python/plugins\inasafe
C:\Users\kurnia\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\kurnia\.qgis2\python\plugins
C:\Users\kurnia\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~1\QGISLY~1\apps\qgis\python\plugins\fTools\tools
C:/Minion/InaSAFE 3.2 Training Data/Nagekeo
```

# Platform
Win 7 64Bit
QGIS 2.8.4 & 2.12.1
InaSAFE 3.2.5.dev-master

@adissadis also get the same thing like this

But, it's OK (the error not occured) When I try in Linux Ubuntu 64-bit, QGIS 2.8.4, InaSAFE 3.2.5dev-3191a00

# cc
@timlinux @ismailsunni @lucernae

**Comment by borysiasty** [comment]
Could someone assign it to me please?
