### ISSUE TITLE
[BUG] Python error in PDF generator and Open in Composer using IFCW

### ISSUE THREAD

**Issue by vasanthi0808** [inasafe/inasafe#2532]
# Problem
Python error when trying to generate the PDF report. 

# Detail
I tried to run the Jakarta flood scenario using vector data for hazard and population raster data for the exposure. Python errorr appeared when trying to generate the report. 
**This problem also happens with other scenarios using IFCW.**
This message appear:
```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/Vasanthi/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 3768, in on_pbnReportPDF_released
    self.analysis_handler.print_map('pdf')
  File "C:/Users/Vasanthi/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 539, in print_map
    print_dialog.buttonBox.addButton(
AttributeError: 'ImpactReportDialog' object has no attribute 'buttonBox'


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.4-Wien Wien, 71ba2c7

Python path: ['C:/Users/Vasanthi/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/Vasanthi/.qgis2/python', u'C:/Users/Vasanthi/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Vasanthi/.qgis2//python', 'C:/Users/Vasanthi/.qgis2/python/plugins\\inasafe', 'C:\\Users\\Vasanthi\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\Vasanthi\\.qgis2\\python\\plugins', 'C:\\Users\\Vasanthi\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', 'D:/WORK!/InaSAFE Freeze Desember/InaSAFE ScenarioData/Flood/Jakarta']
```

# Screenshot
![ifcw pdf](https://cloud.githubusercontent.com/assets/2050209/11950763/fe9f6b08-a8bd-11e5-8000-d18f950dd4ee.png)

# Specification
Windows 7 64 Bit
RAM 4GB
QGIS 2.8.4 Wien
InaSAFE 3.2.5 dev-master

Cc : @timlinux @ismailsunni

**Comment by Gustry** [comment]
Oups, sorry @ismailsunni I saw your assignment after.
There isn't unit test for analysis_handler.py. Maybe we should write some ?

**Comment by ismailsunni** [comment]
@Gustry 
no problem, I can assign it to you happily :dancer: 

> There isn't unit test for analysis_handler.py. Maybe we should write some ?

Yeah, we should do that for sure

Thanks :D

**Comment by ismailsunni** [comment]
Fixed in #2534

**Comment by harrymahar** [comment]
@ismailsunni  I have update my InaSAFE recently using git bash and run flood scenario using IFCW again. However, the result still has python error when I try to generate pdf or open map composer.

**Comment by ismailsunni** [comment]
@harrymahar 
Can you paste here the python error?
And can you paste here your inasafe hash value? *do `git log` and copy the first hash value

**Comment by harrymahar** [comment]
Hai @ismailsunni 
Python Error :
![python error_flood_ifcw](https://cloud.githubusercontent.com/assets/2534179/11970803/cca11736-a963-11e5-9a66-740cda96c0c9.PNG)

git log :
![python error_flood_ifcw_2](https://cloud.githubusercontent.com/assets/2534179/11970805/d767ef6e-a963-11e5-87e3-594089d8c9b9.PNG)

**Comment by ismailsunni** [comment]
hi @harrymahar 
Please try again, I just push my fix to develop.

**Comment by harrymahar** [comment]
Hi @ismailsunni 
Yaay, it is work now.. Thanks
![print composer](https://cloud.githubusercontent.com/assets/2534179/11972239/247e5f50-a97c-11e5-81ed-e6190e5248d3.PNG)

![generate pdf](https://cloud.githubusercontent.com/assets/2534179/11972244/2d31bd54-a97c-11e5-9a82-53708e9af2bf.PNG)
