### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'xMinimum'

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2624]
# problem

When I try to run an IF for tsunami (roads) on the GA computer I get the following python error and then QGIS crashes

```
`An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/u39712/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1159, in accept
    self.analysis = self.prepare_analysis()
  File "C:/Users/u39712/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1273, in prepare_analysis
    analysis.user_extent = self.extent.user_extent
  File "C:/Users/u39712/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 129, in user_extent
    user_extent.xMinimum(),
AttributeError: 'NoneType' object has no attribute 'xMinimum'


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, 313a6bc

Python path: ['C:/Users/u39712/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/u39712/.qgis2/python', u'C:/Users/u39712/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/u39712/.qgis2//python', 'C:/Users/u39712/.qgis2/python/plugins\\inasafe', 'C:\\Users\\u39712\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\u39712\\.qgis2\\python\\plugins', 'C:\\Users\\u39712\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', 'C:/Users/u39712/Desktop/Maumere/Maumere']`
```
_environment_:
Windows, Maumere dataset, InaSAFE Nightly

Using the same data and environment I do not get this problem on my standalone laptop (which connects to GA wifi).

# cc
@Charlotte-Morgan

**Comment by easmetz** [comment]
![image](https://cloud.githubusercontent.com/assets/16660099/12940343/1b68b106-d01c-11e5-99a0-4785fb376837.png)

**Comment by Gustry** [comment]
This error should be fixed with this PR : https://github.com/inasafe/inasafe/pull/2621
I'm waiting for it to be merged.

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz  - this is nothing to do with GA computer. As I mentioned it sounds like the extent selector issue I was telling you about. once its merged a refresh of your nightly builds will fix it.

**Comment by Gustry** [comment]
The PR has been merged in `develop`.
You shouldn't replicate this issue. Feel free to reopen if there is a problem.
