### ISSUE TITLE
TypeError: sequence item 0: expected string, float found while running an IF

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2626]
# Problem 
I'm trying to run an IF building on flood vector, but I'm getting this python error : 
```
2016-02-12 14:44:13,662 - InaSAFE - ERROR - An exception occurred when running the impact analysis.
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 535, in run_analysis
    self.impact_layer = calculate_impact(self.impact_function)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 176, in calculate_impact
    result_layer = impact_function.run()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_functions/generic/classified_polygon_building/impact_function.py", line 198, in run
    impact_summary = impact_table = self.html_report()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_reports/report_mixin_base.py", line 30, in html_report
    return self.generate_report().to_html(suppress_newlines=True)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_reports/building_exposure_report_mixin.py", line 91, in generate_report
    message.add(self.notes())
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_functions/generic/classified_polygon_building/impact_function.py", line 71, in notes
    'zones: %s') % ', '.join(self.hazard_zones))
TypeError: sequence item 0: expected string, float found
```
It works with the test dataset, but I'm working with my own dataset. I'm checking the problem.

**Comment by Gustry** [comment]
I'm using integers in my attribute table and InaSAFE expected some strings instead.
