### ISSUE TITLE
Py error: Flood Vector on Pop Vector

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2686]
The following error occurred:
Env: Windows, InaSAFE tagged version 3.3.0
Data: jakarta flood poly and Jakarta vector population (as supplied by Iwan as test data)

Error message

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 4001, in on_pbnNext_released
    self.go_to_step(new_step)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 3868, in go_to_step
    self.setup_and_run_analysis()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 3822, in setup_and_run_analysis
    self.analysis_handler.setup_and_run_analysis()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 316, in setup_and_run_analysis
    self.analysis.run_analysis()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 599, in run_analysis
    tr('An exception occurred when running the impact analysis.'))
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\common\signals.py", line 163, in analysis_error
    message = get_error_message(exception, context=message)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\utilities.py", line 82, in get_error_message
    problem.append = m.Text(exception.message)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\messaging\item\text.py", line 51, in __init__
    self.add(text)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\messaging\item\text.py", line 70, in add
    raise InvalidMessageItemError(text, text.__class__)
InvalidMessageItemError: (KeyError('area_id_field',), )


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.3-Wien Wien, 313a6bc

Python path: ['C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\bin', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\arcpy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\ArcToolbox', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/AIFDR_ADMIN/.qgis2//python', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\inasafe', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools']
```

**Comment by Charlotte-Morgan** [comment]
This was caused by a missing key word.

Proposed solution - implement the happy warning routine.

**Comment by timlinux** [comment]
For you @ismailsunni - when keywords are missing please provide a nice informative message to the user.

**Comment by ismailsunni** [comment]
See my PR #3003, perhaps it's enough for showing the message.

@Charlotte-Morgan can you tell me what keywords is missing?

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - I can not be sure but it may have been the id field an name field as these are unique for the population vector exposure data

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan or @samnawi can you point me to location of the data? I am bit confused with `jakarta flood poly and Jakarta vector population (as supplied by Iwan as test data)`
Thanks

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - please make sure Kartoza have a sample of this data - maybe the new testdata sync we discussed?

**Comment by Gustry** [comment]
This error is not relevant anymore with V4.
