### ISSUE TITLE
Keywords error for PostgreSQL database layer

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2718]
### Problem

I am trying to set keywords on a database layer. This used to work pre 3.3. Now I get this error:

```
An error has occurred while executing Python code: 

ReadLayerError: Could not read dbname='indonesia' port=5432 sslmode=disable key='id' srid=4326 type=MultiPolygon table="maumere"."buildings" (geom) sql=. Extension "."buildings" (geom) sql=" has not been implemented 
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard_dialog.py", line 3896, in on_pbnNext_released
    self.save_current_keywords()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard_dialog.py", line 4557, in save_current_keywords
    self.dock.get_layers()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 992, in get_layers
    self.draw_rubber_bands()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1138, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2037, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2109, in validate_extents
    analysis = self.prepare_analysis()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1265, in prepare_analysis
    analysis.exposure = self.get_exposure_layer()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 207, in exposure
    self.impact_function.exposure = exposure_layer
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/continuous_rh_classified_ve.py", line 51, in exposure
    ImpactFunction.exposure.fset(self, value)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 344, in exposure
    self._exposure = SafeLayer(convert_to_safe_layer(layer))
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 450, in convert_to_safe_layer
    return safe_read_layer(layer.source())
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 34, in read_layer
    raise ReadLayerError(msg)
ReadLayerError: Could not read dbname='indonesia' port=5432 sslmode=disable key='id' srid=4326 type=MultiPolygon table="maumere"."buildings" (geom) sql=. Extension "."buildings" (geom) sql=" has not been implemented


Python version: 2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] 
QGIS version: 2.14.0-Essen Essen, exported 

Python Path:
/Users/timlinux/.qgis2/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/timlinux/.qgis2/python
/Users/timlinux/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages
/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg
/Library/Python/2.7/site-packages/pycharm-debug.egg
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Library/Python/2.7/site-packages
/Users/timlinux/.qgis2//python
/Users/timlinux/.qgis2/python/plugins/inasafe
/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters
/Users/timlinux/.qgis2/python/plugins
/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras
C:/eclipse/plugins/org.python.pydev_3.6.0.201406232321/pysrc
/Library/Python/2.7/site-packages/IPython/extensions
/Users/timlinux/.qgis2/python/plugins/SGDiagramDownloader/third_party
/Users/timlinux/.qgis2/python/plugins/StreamFeatureExtractor/third_party
.
/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools
```
### Expected Behaviour

We should be able to set keywords for database layers without error.
### Environment

OSX using postgres.app for database backend, InaSAFE develop
### Proposed Solution

@ismailsunni please investigate.

**Comment by timlinux** [comment]
Its also a side effect of trying to convert stuff to read layer....

**Comment by timlinux** [comment]
I should add that besides this error, the keywords are properly stored in the sqlite keywords db and recognised by InaSAFE:

<img width="1359" alt="screen shot 2016-04-08 at 12 00 31" src="https://cloud.githubusercontent.com/assets/178003/14374579/9eeacbc6-fd81-11e5-99da-9b520ed25b32.png">

**Comment by timlinux** [comment]
Another note that when I try to run the IF, I get the same traceback as above again:

```
An error has occurred while executing Python code: 

ReadLayerError: Could not read dbname='indonesia' port=5432 sslmode=disable key='id' srid=4326 type=MultiPolygon table="maumere"."buildings" (geom) sql=. Extension "."buildings" (geom) sql=" has not been implemented 
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1138, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2037, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2109, in validate_extents
    analysis = self.prepare_analysis()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1265, in prepare_analysis
    analysis.exposure = self.get_exposure_layer()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 207, in exposure
    self.impact_function.exposure = exposure_layer
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/continuous_rh_classified_ve.py", line 51, in exposure
    ImpactFunction.exposure.fset(self, value)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 344, in exposure
    self._exposure = SafeLayer(convert_to_safe_layer(layer))
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 450, in convert_to_safe_layer
    return safe_read_layer(layer.source())
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 34, in read_layer
    raise ReadLayerError(msg)
ReadLayerError: Could not read dbname='indonesia' port=5432 sslmode=disable key='id' srid=4326 type=MultiPolygon table="maumere"."buildings" (geom) sql=. Extension "."buildings" (geom) sql=" has not been implemented


Python version: 2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] 
QGIS version: 2.14.0-Essen Essen, exported 

Python Path:
/Users/timlinux/.qgis2/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/timlinux/.qgis2/python
/Users/timlinux/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages
/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg
/Library/Python/2.7/site-packages/pycharm-debug.egg
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
```

**Comment by Gustry** [comment]
We don't use `storage` anymore in version 4. We use now QGIS Layers everywhere.
I'm going to close this issue.
