### ISSUE TITLE
InaSAFE Intermediate Ex. errors: Python error

### ISSUE THREAD

**Issue by airving61** [inasafe/inasafe#2724]
### Problem
I'm trying to work my way through the InaSAFE tutorial exercises, the Basic Exercise went OK, but the [Intermediate Exercise]  (http://docs.inasafe.org/en/training/socialisation/run_intermediate_inasafe.html) part 1  has thrown up a Python error and an OSM downloader error (the latter listed separately)
### Expected Behaviour
Running the application after defining the relevant keywords for 'Jakarta District' dataset should result in a set of statistics regarding the affected population relative to the districts. Instead a warning is received regarding the following Python error: 

```
2016-04-14T12:42:23	1	Traceback (most recent call last):
			  File "C:/Users/airv/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1160, in accept
			    self.analysis.setup_analysis()
			  File "C:/Users/airv/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 311, in setup_analysis
			    self.setup_impact_function()
			  File "C:/Users/airv/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 470, in setup_impact_function
			    self.aggregator.deintersect()
			  File "C:/Users/airv/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 486, in deintersect
			    self.hazard_layer)
			  File "C:/Users/airv/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 1487, in _prepare_polygon_layer
			    int_com.difference(int_sym))
			AttributeError: 'NoneType' object has no attribute 'difference'
```

### Environment
Windows 7 Pro 64bit
QGIS 2.14.1 64bit
InaSAFE 3.3.1

### Proposed Solution
Any useful advice gratefully received

**Comment by timlinux** [comment]
Hi @airving61 My apologies for the delay in replying. I'm testing here for you and will see if I can replicate. I'll update the ticket here with any new info.

For issues with the OSM downloader - these are probably fixed if you install the updated 3.3.2 release - see https://github.com/inasafe/inasafe/releases/tag/version-3_3_2

**Comment by timlinux** [comment]
Seems I am getting a different error:

```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1160, in accept
    self.analysis.setup_analysis()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 311, in setup_analysis
    self.setup_impact_function()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 470, in setup_impact_function
    self.aggregator.deintersect()
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 486, in deintersect
    self.hazard_layer)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 1569, in _prepare_polygon_layer
    self.update_keywords(output_layer, {'title': name})
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 227, in update_keywords
    self._keyword_io.update_keywords(layer, keywords=keywords)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 291, in update_keywords
    existing_keywords = self.read_keywords(layer)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 225, in read_keywords
    keywords = read_file_keywords(source)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/utilities.py", line 314, in read_file_keywords
    raise NoKeywordsFoundError(message)
NoKeywordsFoundError: No keywords file found for /var/folders/hp/1jd4cnzj5h92lq_tjw6bm2gm0000gn/T/inasafe/2016-05-01/timlinux/pre-process/tmpMHX0DJ.keywords


Python version:
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]


QGIS version:
2.8.1-Wien Wien, 

Python path: ['/Applications/QGIS2.8.1.app/Contents/MacOS/../Resources/python/plugins/processing', '/Applications/QGIS2.8.1.app/Contents/MacOS/../Resources/python', u'/Users/timlinux/.qgis2/python', u'/Users/timlinux/.qgis2/python/plugins', '/Applications/QGIS2.8.1.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/pip-6.1.1-py2.7.egg', '/Library/Python/2.7/site-packages/pycharm-debug.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/timlinux/.qgis2//python', '/Users/timlinux/.qgis2/python/plugins/inasafe', '/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters', '/Users/timlinux/.qgis2/python/plugins', '/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras', 'C:/eclipse/plugins/org.python.pydev_3.6.0.201406232321/pysrc', '/Library/Python/2.7/site-packages/IPython/extensions', '/Users/timlinux/.qgis2/python/plugins/SGDiagramDownloader/third_party', '/Users/timlinux/.qgis2/python/plugins/StreamFeatureExtractor/third_party', '.', '/Applications/QGIS2.8.1.app/Contents/Resources/python/plugins/fTools/tools', '/Users/timlinux/gisdata/InaSAFEHotTrainingData/Run Intermediate InaSAFE/DKI Jakarta']
```

**Comment by timlinux** [comment]
Note that the above error is encountered when 'show intermediate aggregation layer' option is enabled.

**Comment by timlinux** [comment]
With the show intermediate aggregation layer option disabled I get:

```
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 552, in run_analysis self.impact_layer = calculate_impact(self.impact_function)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 170, in calculate_impact check_data_integrity(layers)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 66, in check_data_integrity verify(keyword in keywords, message)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/common/utilities.py", line 64, in verify raise VerificationError(message)
```

With notes:

* An exception occurred when running the impact analysis.
* Layer did not have required keyword "layer_purpose". Please add keywords as : pairs in the .xml file. For more information please read the sections on impact functions and keywords in the InaSAFE website: http://inasafe.org/en/developer-docs/

**Comment by timlinux** [comment]
@ismailsunni could you take a look at this please? It seems to be a side effect of the keywords refactor stuff. Also note the different error when enabling the 'show intermediate layers' option above.

**Comment by timlinux** [comment]
@ismailsunni please also back port to master.

**Comment by ismailsunni** [comment]
Hi @airving61 @timlinux 
I have tried in my local, using develop. All is fine. With enable or disable `show intermediate layers` above.

Can you guys try again with develop? Please re-assign the keywords for hazard, since it's not detected by InaSAFE.

**Comment by ismailsunni** [comment]
Hi again

I tried in master, and it fails like you mentioned above. Should we fix the master, or wait for develop?

Best regards

**Comment by ismailsunni** [comment]
hi @timlinux and @airving61 
I have made a PR to address this issue in #2775. I have checked in my QGIS, all is fine for both case (enable and disable intermediate layer).
