### ISSUE TITLE
its a dummy ticket

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#2755]
I'm still learning how to write a ticket :)
# Problem

# CC
@felix_yew @samnawi @lucernae

**Comment by samnawi** [comment]
Make it happy

**Comment by felix-yew** [comment]
Great +1

**Comment by ismailsunni** [comment]
hi @ivanbusthomi 
just suggestion, if you open new issue, there is a template. Please make sure all the fields are filled, to make the developer's life easier :)

If you have python error message or trace back, don't post the screenshot. It's better to copy the text and paste here as text. For example:
```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/gui/tools/wizard/wizard_dialog.py", line 736, in on_pbnNext_released
    new_step.set_widgets()
  File "/Users/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/gui/tools/wizard/step_kw65_summary.py", line 116, in set_widgets
    current_keywords = self.parent.get_keywords()
  File "/Users/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe/gui/tools/wizard/wizard_dialog.py", line 788, in get_keywords
    keywords.update(self.get_aggregation_attributes())
AttributeError: 'WizardDialog' object has no attribute 'get_aggregation_attributes'


Python version:
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]


QGIS version:
2.8.3-Wien Wien, 

Python path: ['/Users/ismailsunni/.qgis2/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/ismailsunni/.qgis2/python', u'/Users/ismailsunni/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/ismailsunni/.qgis2//python', '/Users/ismailsunni/.qgis2/python/plugins/inasafe-dev', '/Users/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe_extras/parameters', '/Users/ismailsunni/.qgis2/python/plugins', '/Users/ismailsunni/.qgis2/python/plugins/inasafe-dev/safe_extras', '/Users/ismailsunni/.qgis2/python/plugins/SGDiagramDownloader/third_party', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/ismailsunni/Documents/gis_data']
```

You can stop until the `Python version` line if you want to avoid showing some privacy.

Cheers

**Comment by ivanbusthomi** [comment]
@Charlotte-Morgan  please make me a collaborator

**Comment by felix-yew** [comment]
```

tes

```

**Comment by lucernae** [comment]
You can also do this:
- [ ] Some to do list
- [ ] To do list no. 2

You can use 

# Heading LVL 1

## Heading LVL 2

or link to another ticket #2755

**Comment by Gustry** [comment]
And you can add some labels, assign the ticket to someone or add a milestone ;-)

**Comment by Charlotte-Morgan** [comment]
ha ha - the new team have limited access to assign tickets right now, also not able to move or close things

**Comment by ivanbusthomi** [comment]
# Styling a comment
This **text** is bold and this _one_ is italized.

here are some error codes sample that I attached
```
warning:C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py:844: PendingDeprecationWarning: This method will be removed in future versions.  Use 'elem.iter()' or 'list(elem.iter())' instead.
```

> And you can add some labels, assign the ticket to someone or add a milestone ;-)

I can't do that, yet. But i can write a quote :+1: 

and here are my todos for now:

- [x] Create a task list
- [ ] Contribute more
