### ISSUE TITLE
[Bug]  IFCW: Cannot set "No Aggregation" if the previous action is using Aggregation

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2818]
### Problem
This minor bug appear when i previously run analysis using IFCW with aggregation. When i tried to run the second analysis without close the QGIS first (using the same QGIS and the same data that already loaded in QGIS layer list) and i don't using aggregation in this second analysis, the IFCW will read the aggregation layer in the end of the summary information before run the analysis.

Here's step to produce this error:

1. Click IFCW
2. Select hazard type, add hazard, add exposure and select using aggregation first.
3. The InaSAFE will successfully run Analysis using aggregation
4. Without close the QGIS first, click IFCW again and try to run the same hazard analysis
5. Select hazard & exposure that already in the layer list
6. Do not select the aggregation layer. Choose "No thanks, I'm happy to aggregate results for entire analysis window" and click Next.
7. Select analysis area and postprocessor
8. In the IFCW analysis summary, you will realize that IFCW will still using aggregation layer even though you already define not to use aggregation 

This bug only occur when you run IFCW using aggregation first and then you run IFCW for the second time for the same hazard but without aggregation.

### Expected Behaviour
If the user run IFCW first time using aggregation and in the second time the user run IFCW without aggregation, the IFCW will do the analysis based on the user input in the aggregation section (the user select "No thanks, I'm happy to aggregate results for entire analysis window"

### Environment
Windows 10 64bit 16GB
QGIS 2.8.9 InaSAFE 3.4 from github

**Comment by ismailsunni** [comment]
Hi @adissadis 
I follow the steps that you wrote, but I can't reproduce it.

Can you ask anyone in Thamrin to replicate it ?

**Comment by borysiasty** [comment]
@ismailsunni please see #2822

**Comment by adissadis** [comment]
@ismailsunni i already tested on another laptop but this problem still occured

I found python error after i delete the aggregation layer. This is the python error:

```
An error has occurred while executing Python code:


Traceback (most recent call last):
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\wizard_dialog.py", line 706, in on_pbnNext_released
    new_step = current_step.get_next_step()
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_fc70_extent.py", line 76, in get_next_step
    if self.validate_extent():
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_fc70_extent.py", line 89, in validate_extent
    _analysis_handler.setup_analysis()
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 337, in setup_analysis
    self.impact_function.aggregation = self.parent.aggregation_layer
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 432, in aggregation
    self._aggregation = SafeLayer(layer)
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\storage\safe_layer.py", line 46, in __init__
    self.layer = layer
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\storage\safe_layer.py", line 84, in layer
    self.keywords = keyword_io.read_keywords(layer)
  File "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\utilities\keyword_io.py", line 210, in read_keywords
    source = layer.source()
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.9-Wien Wien, 26c3ece

Python path: ['C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/Adityo/.qgis2/python', u'C:/Users/Adityo/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/Adityo/.qgis2//python', 'C:/Users/Adityo/.qgis2/python/plugins\\inasafe', 'C:\\Users\\Adityo\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\Adityo\\.qgis2\\python\\plugins', 'C:\\Users\\Adityo\\.qgis2\\python\\plugins\\inasafe\\safe_extras', 'C:\\Users\\Adityo\\.qgis2\\python\\plugins\\MetaSearch\\ext-libs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', 'C:\\Users\\Adityo\\.qgis2\\python\\plugins\\mmqgis/forms']
```

**Comment by ismailsunni** [comment]
Hi @adissadis 
If you still found the error/bug, please re-open the issue.

Can you explain more, when do you delete the aggregation layer? After closing the wizard? Or how?

Thanks

**Comment by adissadis** [comment]
That python error found before i check fix from borys. So you can close it now. Thank you!
