### ISSUE TITLE
Python Error on Tsunami Raster vs Population Raster

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#2886]
### Problem
So I run InaSAFE 3.4 using tsunami raster hazard on raster population exposure. I tried using ambon data and I got this error message.
```
Traceback (most recent call last):
			  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1164, in accept
			    self.impact_function.run_analysis()
			  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 726, in run_analysis
			    tr('An exception occurred when running the impact analysis.'))
			  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\common\signals.py", line 163, in analysis_error
			    message = get_error_message(exception, context=message)
			  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\utilities\utilities.py", line 81, in get_error_message
			    problem.append = m.Text(exception.message)
			  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\messaging\item\text.py", line 51, in __init__
			    self.add(text)
			  File "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\messaging\item\text.py", line 70, in add
			    raise InvalidMessageItemError(text, text.__class__)
			InvalidMessageItemError: (ExpatError('not well-formed (invalid token): line 24, column 39',), <class 'xml.parsers.expat.ExpatError'>)
```

this is my keyword setup for ambon data that produce the python error
![keyword](https://cloud.githubusercontent.com/assets/7351977/15672556/952ed56a-275b-11e6-8de4-1c9c338ad190.PNG)

furthermore, when i tried using the IFCW, it didn't read the layer that i've loaded to QGIS eventhough the keyword was already set.
![ifcw](https://cloud.githubusercontent.com/assets/7351977/15672683/4aaa70d4-275c-11e6-9f21-4d22ede58e9a.PNG)

___
when I tried using another dataset (Maumere Tsunami), I got no error and the result is looking pretty good.
![maumere](https://cloud.githubusercontent.com/assets/7351977/15672795/035acb56-275d-11e6-9b3b-fa3fdb64a98f.PNG)

### Expected Behaviour
I expected i dont get any error since @felix-yew and @Charlotte-Morgan have tried using the exact data, and theirs are working.

### Environment
* InaSAFE : 3.4
* QGIS : 2.14.1
* OS : Windows 7 64 bit
* Data used : This is the data :point_right: [data.zip](https://github.com/inasafe/inasafe/files/290963/data.zip)
  * Exposure : Raster Population
  * Hazard : Continuous Raster Tsunami Hazard Ambon
  * Aggregation : No

### Proposed Solution
Make it happy

cc: @felix-yew @samnawi @Charlotte-Morgan @ismailsunni

**Comment by felix-yew** [comment]
Just add some information related this issue. I have try the same data. In my Windows 7 64-bit, run with QGIS 2.14.1 and the process can work properly.

![image](https://cloud.githubusercontent.com/assets/13621886/15673180/29da64f6-275f-11e6-9b08-183e88a28c04.png)
But, maybe the result have a little strange, because just in a small area that affected and not suitable with the table result that has explain in each hazard zone, related to the map result.

Make it happy :smile:

**Comment by Gustry** [comment]
I got this error too : 
```
InvalidMessageItemError: (ExpatError('not well-formed (invalid token): line 24, column 39',), ) 
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1164, in accept
    self.impact_function.run_analysis()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 726, in run_analysis
    tr('An exception occurred when running the impact analysis.'))
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/common/signals.py", line 163, in analysis_error
    message = get_error_message(exception, context=message)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/utilities.py", line 81, in get_error_message
    problem.append = m.Text(exception.message)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/messaging/item/text.py", line 51, in __init__
    self.add(text)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/messaging/item/text.py", line 70, in add
    raise InvalidMessageItemError(text, text.__class__)
InvalidMessageItemError: (ExpatError('not well-formed (invalid token): line 24, column 39',), )
```
This error has been caught by InaSAFE but by QGIS.

**Comment by ismailsunni** [comment]
After one hours deep debugging, I found that the `&` character in the exposure layer name is the problem.

The reason is because we will save it in the xml, and it's one of the special character in xml. See more about special character in xml here : https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

The other special characters are: `" ' < > ` (double quotation mark, apostrophe, less-than sign, greater-than sign). Please avoid to use those characters.

**Comment by Charlotte-Morgan** [comment]
The problem of not much data on the map occurs if the user overwrites the default threshold of 0.7

This issue is now understood, fixed and can be closed
