### ISSUE TITLE
MetadataReadError while loading a layer

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2945]
### Problem
I opened the file `West Sumatera/01 Hazard Data/Padang_EQ_2009_WGS84.tif` from `data.inasafe.org` : 

```
An error has occurred while executing Python code: 

MetadataReadError: No keyword version found. Metadata xml file is invalid. Layer uri: /home/etienne/kartoza_dev/inasafe/dataset/West Sumatera/01 Hazard Data/Padang_EQ_2009_WGS84.tif Keywords file: True keywords: license: Free use with accreditation title: InaSAFE analysis result url: PyQt4.QtCore.QUrl(u'http://inasafe.org') organisation: InaSAFE.org abstract: InaSAFE analysis result date: 2015-07-27 00:00:00 email: info@inasafe.org 
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 924, in get_layers
    self.keyword_io.update_keywords(layer, {'title': name})
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 214, in update_keywords
    existing_keywords = self.read_keywords(layer)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 181, in read_keywords
    return read_iso19115_metadata(source, keyword)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/metadata.py", line 110, in read_iso19115_metadata
    raise MetadataReadError(message)
MetadataReadError: No keyword version found. Metadata xml file is invalid.
Layer uri: /home/etienne/kartoza_dev/inasafe/dataset/West Sumatera/01 Hazard Data/Padang_EQ_2009_WGS84.tif
Keywords file: True
keywords:
license: Free use with accreditation
title: InaSAFE analysis result
url: PyQt4.QtCore.QUrl(u'http://inasafe.org')
organisation: InaSAFE.org
abstract: InaSAFE analysis result
date: 2015-07-27 00:00:00
email: info@inasafe.org
```

### Environment
* InaSAFE : Develop

**Comment by timlinux** [comment]
This should be fixed already?

**Comment by Gustry** [comment]
Thanks @ismailsunni , I can't replicate
