### ISSUE TITLE
MemoryError while saving new keywords to a EQ raster

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2947]
### Problem
I opened a EQ raster in InaSAFE. The file is `West Sumatera/01 Hazard Data/Padang_EQ_2009_WGS84.tif` from data.inasafe.org. I got the error #2945 so I removed the xml file manually and I opened the layer again. I was setting the new keyword, but after the last step, when the wizard is writing the new keywords, I got this error, after a small freeze : 
```
An error has occurred while executing Python code: 

MemoryError 
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard/wizard_dialog.py", line 677, in on_pbnNext_released
    self.save_current_keywords()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard/wizard_dialog.py", line 851, in save_current_keywords
    self.dock.get_layers()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 985, in get_layers
    self.draw_rubber_bands()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1131, in draw_rubber_bands
    self.show_next_analysis_extent()  # green
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2107, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2179, in validate_extents
    impact_function = self.prepare_impact_function()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1255, in prepare_impact_function
    impact_function.exposure = self.get_exposure_layer()
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/continuous_rh_continuous_re.py", line 47, in exposure
    ImpactFunction.exposure.fset(self, value)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 398, in exposure
    self._exposure = SafeLayer(convert_to_safe_layer(layer))
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 463, in convert_to_safe_layer
    return safe_read_layer(layer.source())
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 28, in read_layer
    return Raster(filename)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/storage/raster.py", line 107, in __init__
    self.read_from_file(data)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/storage/raster.py", line 269, in read_from_file
    NaN = numpy.ones((M, N), numpy.float64) * numpy.nan
MemoryError
```

So I had to close the keyword wizard with the "cross button". Now I have this error every time I pan/zoom my map canvas : a small freeze then the python error.

### Expected Behaviour
The error should be handled gracefully.

### Environment
* InaSAFE : Develop
* QGIS : 2.14.3
* OS : Ubuntu 14.04, 6 GO ram, the raster is only 3mo.
* Data used :
  * Hazard : West Sumatera/01 Hazard Data/Padang_EQ_2009_WGS84.tif

**Comment by Gustry** [comment]
I got another MemoryError today, I made a fix. I was trying to fix this one too at the same time, but I can't replicate anymore.
