### ISSUE TITLE
database connection error on volcano sample data in inasafe repo

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2980]
### Problem

Trying to run volcano on building  from a volcano hazard loaded in a postgres  database results in connection error.

`An error has occurred while executing Python code: 
ReadLayerError: Could not read dbname='inasafe' host=localhost port=5432 user='admire' password='user' sslmode=disable key='gid' srid=4326 type=MultiPolygon table="public"."volcano_krb" (geom) sql=. Extension "."volcano_krb" (geom) sql=" has not been implemented 
Traceback (most recent call last):
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2041, in define_user_analysis_extent
    self.show_next_analysis_extent()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2109, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2181, in validate_extents
    impact_function = self.prepare_impact_function()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1254, in prepare_impact_function
    impact_function.hazard = self.get_hazard_layer()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/classified_vh_classified_ve.py", line 48, in hazard
    ImpactFunction.hazard.fset(self, value)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 363, in hazard
    self._hazard = SafeLayer(convert_to_safe_layer(layer))
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 463, in convert_to_safe_layer
    return safe_read_layer(layer.source())
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 34, in read_layer
    raise ReadLayerError(msg)
ReadLayerError: Could not read dbname='inasafe' host=localhost port=5432 user='admire' password='user' sslmode=disable key='gid' srid=4326 type=MultiPolygon table="public"."volcano_krb" (geom) sql=. Extension "."volcano_krb" (geom) sql=" has not been implemented`

![io](https://cloud.githubusercontent.com/assets/2510900/16269482/c4817848-3892-11e6-93c6-205353f959de.png)
### Expected Behaviour

Run without an errors.
### Environment
- InaSAFE : 3.5
- QGIS : 2.14.3
- OS : Ubuntu 16.04
- Data used : `.qgis2/python/plugins/inasafe/safe/test/data/`
  - Exposure : `Buildings from OSM`
  - Hazard : `hazard/volcano_krb` loaded in postgres database
  - Aggregation : `Entire Area`
### Proposed Solution

Run without errors.

**Comment by Gustry** [comment]
We are not using `storage` anymore in version 4. We use QGIS Layers now. I'm going to close this issue.
