### ISSUE TITLE
InaSAFE plugin will not load - no module named raven.handlers.logging

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3070]
### Problem
The InaSAFE plugin will not load (either on startup of QGIS, or through toggling the plugin in Plugin Manager and comes up with this error:

![image](https://cloud.githubusercontent.com/assets/16660099/17126693/a91feace-5329-11e6-970a-60681b2f10be.png)

```
Couldn't load plugin inasafe due to an error when calling its classFactory() method 

ImportError: No module named raven.handlers.logging 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS21~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\__init__.py", line 86, in classFactory
    from safe.plugin import Plugin
  File "C:/PROGRA~1/QGIS21~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\__init__.py", line 28, in 
    from safe.common.custom_logging import setup_logger
  File "C:/PROGRA~1/QGIS21~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\__init__.py", line 28, in 
    from safe.common.custom_logging import setup_logger
  File "C:/PROGRA~1/QGIS21~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\common\custom_logging.py", line 22, in 
    from raven.handlers.logging import SentryHandler
  File "C:/PROGRA~1/QGIS21~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named raven.handlers.logging


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.4-Essen Essen, 634f24b 
```

### Environment
* InaSAFE : develop
* OS : Windows 7
I updated from QGIS 2.14.1 to QGIS 2.14.4. It didn't make a difference.

### Proposed Solution
make it happy

### cc
@Charlotte-Morgan @timlinux @ivanbusthomi @felix-yew @fredychandra

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - is it possible that something that was merged yesterday is causing this problem?

**Comment by timlinux** [comment]
> hi @timlinux - is it possible that something that was merged yesterday is causing this problem?

Yes I found the culprit.

![screen shot 2016-07-26 at 2 49 00 pm](https://cloud.githubusercontent.com/assets/178003/17138375/45703486-5340-11e6-8529-0ab40459ddc2.png)

```
diff --git a/safe/common/custom_logging.py b/safe/common/custom_logging.py
index 9a6b45f..0e3e27d 100644
--- a/safe/common/custom_logging.py
+++ b/safe/common/custom_logging.py
@@ -12,32 +12,29 @@ Contact : ole.moller.nielsen@gmail.com
 
 """
 
-__author__ = 'tim@kartoza.com'
-__revision__ = '$Format:%H$'
-__date__ = '29/01/2011'
-__copyright__ = 'Copyright 2012, Australia Indonesia Facility for '
-__copyright__ += 'Disaster Reduction'
-
 import os
 import sys
 import logging
-
 from qgis.core import QgsMessageLog
 from PyQt4.QtCore import QSettings
-
-safe_extras_dir = os.path.abspath(
-    os.path.join(os.path.dirname(__file__), '..', '..', 'safe_extras'))
-if safe_extras_dir not in sys.path:
-    sys.path.append(safe_extras_dir)
 # pylint: disable=F0401
 # noinspection PyUnresolvedReferences,PyPackageRequirements
 from raven.handlers.logging import SentryHandler
 # noinspection PyUnresolvedReferences,PyPackageRequirements
 from raven import Client
 # pylint: enable=F0401
-
 from safe.common.utilities import log_file_path
 from safe.utilities.i18n import tr
+safe_extras_dir = os.path.abspath(
+    os.path.join(os.path.dirname(__file__), '..', '..', 'safe_extras'))
+if safe_extras_dir not in sys.path:
+    sys.path.append(safe_extras_dir)
+
+__author__ = 'tim@kartoza.com'
+__revision__ = '$Format:%H$'
+__date__ = '29/01/2011'
+__copyright__ = 'Copyright 2012, Australia Indonesia Facility for '
+__copyright__ += 'Disaster Reduction'
```

I will make a PR with a fix in a minute.

**Comment by ThiagoTasSilva** [comment]
Hey guys, what was the solution of this error?

I have the same problem.

**Comment by Gustry** [comment]
Did you update from an old InaSAFE version?
If yes, try to remove your inasafe folder in .qgis2/python/plugins and then reinstall it.

**Comment by ThiagoTasSilva** [comment]
Hey Gustry, thanks for your reply.

I'm trying to create y own plugin and this error is happening with it. Do you know how this problem was solved?

Thanks again...!
