### ISSUE TITLE
Failure to use other vector formats as impact/hazard layers

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#3097]
### Problem

When using a geojson vector layer as a hazard layer, it does not give an error when generating keywords but does not generate any xml with keywords. So trying to run the impact function results in error.

```
An error has occurred while executing Python code: 

ReadLayerError: Could not read /home/admire/Downloads/export.geojson. Extension ".geojson" has not been implemented 
Traceback (most recent call last):
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1157, in accept
    self.show_next_analysis_extent()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2131, in show_next_analysis_extent
    valid, extents = self.validate_extents()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 2203, in validate_extents
    impact_function = self.prepare_impact_function()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1269, in prepare_impact_function
    impact_function.hazard = self.get_hazard_layer()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/bases/classified_vh_continuous_re.py", line 42, in hazard
    ImpactFunction.hazard.fset(self, value)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 366, in hazard
    self._hazard = SafeLayer(convert_to_safe_layer(layer))
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 463, in convert_to_safe_layer
    return safe_read_layer(layer.source())
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/storage/core.py", line 34, in read_layer
    raise ReadLayerError(msg)
ReadLayerError: Could not read /home/admire/Downloads/export.geojson. Extension ".geojson" has not been implemented
```

After creating keywords the dock actually selects the layer although no keywords .xml is generated.
![tza](https://cloud.githubusercontent.com/assets/2510900/17288679/94cc801c-57d6-11e6-8c54-e7eb5dc2d202.png)
### Expected Behaviour

Support using various vector formats as hazard/exposure layers.
### Environment
- InaSAFE :  3.5
- QGIS : Master
- OS :  16.04
- Data used :
  - Exposure :  
  - Hazard :  Wetlands from [tanzania](http://overpass-turbo.eu/)
  - Aggregation :
### Proposed Solution

Implement multiple vector formats if they are not yet supported .

**Comment by Gustry** [comment]
GeoJSON is working fine in InaSAFE V4 now, I will close this ticket.
