### ISSUE TITLE
Find odd number in analysis result when run tsunami raster on population raster

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3464]
### Problem
I try the new architecture InaSAFE 4.0 develop with the new technical git submodule update. I have clipped the area analysis only in Ambon city, and it can produce 'aggregate hazard impacted' as the impacted layer analysis but the number of Count is strange. Not only in the Analysis Results but also in Minimum Needs results, there are no thousand separators.
![image](https://cloud.githubusercontent.com/assets/13621886/20506753/ce60c580-b088-11e6-846f-4334d46aebf9.png)
And, this is from Phyton Console code :
```
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1131
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1135
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1135
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1135
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1135
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1135
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_function.py, line 1131
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_report.py, line 571
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 875, in emit
    self.flush()
  File "C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\logging\__init__.py", line 835, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file impact_report.py, line 571
```

### Expected Behaviour
The results of analysis and minimum needs have a thousand separators to an easy read.

### Environment
* InaSAFE : 4.0.0.dev-master
* QGIS : 2.14.7 Essen
* OS : Windows 7 Professional 64-bit, RAM 12 GB
* Data used :
The data will be shared in the Real World Data (share data test document) - via btsync
Real World Data\Tsunami\Ambon_clip
* Hazard : Ambon_Tsunami_FD_30m_WGS84.tif in Real World Data\Tsunami\Ambon_clip\01 Hazard\Raster
* Exposure : Ambon_Population_WGS84.tif in Real World Data\Tsunami\Ambon_clip\02 Exposure\Population

### Proposed Solution
Make it happy :smile:

**Comment by lucernae** [comment]
mas @felix-yew Is this still a problem?

**Comment by felix-yew** [comment]
Hi, mas @lucernae - sorry for the delay, we still check the raster population data that I use before. But, I try with the other raster population data from inaRISK, it can work properly and show the good result, too.
![image](https://cloud.githubusercontent.com/assets/13621886/23242481/98366c1e-f9ab-11e6-9c69-aa4bfc32d68c.png)
LGTM :+1:
