### ISSUE TITLE
Odd number in hazard raster vs population raster result

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3617]
### Problem
I try to run the hazard raster vs population raster and I get the odd number. In the analysis results,
![image](https://cloud.githubusercontent.com/assets/13621886/22010530/60c355fa-dcbc-11e6-9f85-e886fbd6ce43.png)
and detailed minimum needs report
![image](https://cloud.githubusercontent.com/assets/13621886/22010726/908483a8-dcbd-11e6-9a10-e571d1251452.png)

But, I also get the error message.
```
An error has occurred while executing Python code: 

KeyError: '-1' 
Traceback (most recent call last):
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 793, in accept
    generate_impact_report(self.impact_function, self.iface)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\analysis_utilities.py", line 55, in generate_impact_report
    impact_report.process_component()
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\impact_report.py", line 599, in process_component
    context = _extractor_method(self, component)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\extractors\infographics.py", line 178, in population_infographic_extractor
    analysis_layer)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\extractors\util.py", line 121, in value_from_field_name
    return analysis_layer.getFeatures().next()[field_index]
KeyError: '-1'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.10-Essen Essen, 057b42a 
```
This message error also occurs, when I run the flood raster vs population raster. Similar in ticket #3615 

### Expected Behaviour
The impact function can be running well and get the proper result.

### Environment
* InaSAFE : 4.0.0b0
* QGIS : 2.14.10
* OS : Win7Pro 64-bit/12 GB
* Data used :
  * Exposure : Population Raster
  * Hazard : Tsunami Raster
  * Aggregation : No

### Proposed Solution
Make it happy

Cc:
@Charlotte-Morgan @timlinux @samnawi @ismailsunni @lucernae @Gustry

**Comment by ismailsunni** [comment]
Hi @felix-yew
Can you test it again from develop? I got similar error, and @lucernae has pushed a fix to develop.

**Comment by felix-yew** [comment]
Ok mas @ismailsunni

**Comment by felix-yew** [comment]
Hi mas @ismailsunni - I still get error message

```
An error has occurred while executing Python code: 

KeyError: '-1' 
Traceback (most recent call last):
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 795, in accept
    self.impact_function, self.iface)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\analysis_utilities.py", line 55, in generate_impact_report
    return impact_report.process_component()
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\impact_report.py", line 640, in process_component
    context = _extractor_method(self, component)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\extractors\infographics.py", line 178, in population_infographic_extractor
    analysis_layer)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\extractors\util.py", line 121, in value_from_field_name
    return analysis_layer.getFeatures().next()[field_index]
KeyError: '-1'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.10-Essen Essen, 057b42a 
```

try with the same data.

**Comment by felix-yew** [comment]
When I try earthquake raster vs population raster, I get different error message

```
Problem

The following problem(s) were encountered whilst running the analysis.

AssertionError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Diagnostics

In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 925, in run self._run()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1072, in _run self.damage_curve_analysis()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1174, in damage_curve_analysis self.earthquake_raster_population_raster()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1196, in earthquake_raster_population_raster self.hazard.extent())
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gis\raster\rasterize.py", line 83, in rasterize_vector_layer assert layer_aligned.isValid()
```

Data used :
Exposure : Population Raster
Hazard : Padang Earthquake Raster
Aggregation : No

Cc: @Gustry @ismailsunni

**Comment by ivanbusthomi** [comment]
Hi mas @felix-yew , I've moved your comment https://github.com/inasafe/inasafe/issues/3617#issuecomment-273674821 to a new issues in https://github.com/inasafe/inasafe/issues/3679. Hopefully, if the new issue is fixed this issue here will also be fixed, and we can close both of them.

**Comment by felix-yew** [comment]
Thank you @ivanbusthomi - copy that.

**Comment by Gustry** [comment]
![screen shot 2017-02-01 at 17 54 58](https://cloud.githubusercontent.com/assets/1609292/22516899/9f32359e-e8a7-11e6-8c93-459b144058ec.png)

Can we close this issue @felix-yew ? I could run an analysis with a tsunami on population.

**Comment by felix-yew** [comment]
Hi @Gustry that's nice, I try and it fixes. Thank you. 
![image](https://cloud.githubusercontent.com/assets/13621886/22535505/33e79c7a-e92e-11e6-93fb-053dbda17ff2.png)
:+1: :+1: :+1:
