### ISSUE TITLE
Python error : Landcover Exposure Keyword Setup

### ISSUE THREAD

**Issue by fredychandra** [inasafe/inasafe#3811]
### Problem

I get python error while set up the Exposure Keyword.

```
An error has occurred while executing Python code: 

InvalidExtentError: None is not a valid extent. 
Traceback (most recent call last):
  File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 513, in on_aggregation_layer_combo_currentIndexChanged
    self.validate_impact_function()
  File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1197, in validate_impact_function
    impact_function.requested_extent = wkt_to_rectangle(wkt)
  File "C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 455, in requested_extent
    raise InvalidExtentError('%s is not a valid extent.' % extent)
InvalidExtentError: None is not a valid extent.


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.10-Essen Essen, 057b42a 

Python Path:
C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\processing
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python
C:/Users/chandf.DMINNOVATION/.qgis2/python
C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\bin\python27.zip
C:\PROGRA~1\QGIS2~1.14\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.14\bin
C:\PROGRA~1\QGIS2~1.14\apps\Python27
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/chandf.DMINNOVATION/.qgis2//python
C:/Users/chandf.DMINNOVATION/.qgis2/python/plugins\inasafe
C:\Users\chandf.DMINNOVATION\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\chandf.DMINNOVATION\.qgis2\python\plugins
C:\Users\chandf.DMINNOVATION\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~1\QGIS2~1.14\apps\qgis-ltr\python\plugins\fTools\tools
C:/00. Fredy's/00. DM_Specialist_File/00. INASAFE/5. InaSafe Review/landcover impact
```
### Expected Behaviour
Make it work :) 

### Environment
* InaSAFE : InaSAFE 4.0 Develop
* QGIS : 2.14.10
* OS : Windows 8
* Data used :
  * Exposure : Landcover BIG
  * Hazard : Bojonegora Flood
  * Aggregation :

### Proposed Solution

@timlinux @ismailsunni @Gustry @felix-yew @samnawi @ivanbusthomi @Charlotte-Morgan

**Comment by ismailsunni** [comment]
Hi @fredychandra 
Can you explain how did you get this error? You said you got it while set up exposure keywords. Is it from wizard?
I check the error message, it's related to dock / impact function.

**Comment by Gustry** [comment]
After setting the keywords ?

**Comment by fredychandra** [comment]
Hi @ismailsunni and @Gustry 
I got the error while I set up the keywords creation wizard, but after I git pull and check it out again a minute ago. it has worked  :)

**Comment by ismailsunni** [comment]
@fredychandra can we close this then? :)

**Comment by fredychandra** [comment]
Ok om @ismailsunni we can go forward.

**Comment by ismailsunni** [comment]
Thanks
