### ISSUE TITLE
PetaJakarta downloader fails with requests error

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3834]
### Problem

Trying to use PetaJakarta downloader on QGIS Windows gives an error:

```
Traceback (most recent call last):
			  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\plugin.py", line 848, in add_petajakarta_layer
			    from safe.gui.tools.peta_jakarta_dialog import PetaJakartaDialog
			  File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\gui\tools\peta_jakarta_dialog.py", line 18, in <module>
			    import requests
			  File "C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named requests
			
```

### Expected Behaviour

We should **never** use requests - all network access should go though QGIS Network Manager class to be proxy friendly.

### Environment
* InaSAFE : dev
* QGIS : 2.14.11
* OS : Windows 10

### Proposed Solution

Update to use QGIS Libs for network requests.

**Comment by myarjunar** [comment]
closed in #3858
