### ISSUE TITLE
KW Wizard traceback on windows

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3837]
### Problem

Setting keywords on windows for JK Subdistricts raises an exception which is not caught:

![screencapture](https://cloud.githubusercontent.com/assets/178003/22903772/8417967e-f242-11e6-8d5b-8193c3dcfb17.gif)

```
An error has occurred while executing Python code: 

AttributeError: 'DefaultSelectParameterWidget' object has no attribute 'input_layout' 
Traceback (most recent call last):
  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\wizard_dialog.py", line 657, in on_pbnNext_released
    new_step.set_widgets()
  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_kw47_default_inasafe_fields.py", line 177, in set_widgets
    self.parameter_container.setup_ui()
  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe_extras\parameters\qt_widgets\parameter_container.py", line 191, in setup_ui
    parameter_widget = self.qt4_parameter_factory.get_widget(parameter)
  File "C:\Users\Tim\.qgis2\python\plugins\inasafe\safe_extras\parameters\qt_widgets\qt4_parameter_factory.py", line 73, in get_widget
    return self.dict_widget[class_name](parameter)
  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\common\parameters\default_select_parameter_widget.py", line 63, in __init__
    self.input_layout.setParent(None)
AttributeError: 'DefaultSelectParameterWidget' object has no attribute 'input_layout'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.11-Essen Essen, 2d09b0b 

Python Path:
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python
C:/Users/Tim/.qgis2/python
C:/Users/Tim/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\bin\python27.zip
C:\PROGRA~1\QGIS2~1.14\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.14\bin
C:\PROGRA~1\QGIS2~1.14\apps\Python27
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Tim/.qgis2//python
C:/Users/Tim/.qgis2/python/plugins\inasafe
C:\Users\Tim\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\Tim\.qgis2\python\plugins
C:\Users\Tim\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~1\QGIS2~1.14\apps\qgis-ltr\python\plugins\fTools\tools
E:/Sync/data.inasafe.org/InaSAFE 3.5 Training Data/DKI Jakarta/DKI Jakarta
```

### Environment
* InaSAFE : develop
* QGIS : 2.14.11
* OS :  Windows 10 Pro
* Data used (filenames and paths so as to reproduce):
  * Exposure : 
  * Hazard : 
  * Aggregation : Jakarta Subdistricts

### Proposed Solution

@ismailsunni make it haaaaaaaaaaapy

**Comment by timlinux** [comment]
Ah maybe it is just not up to date parameters...

**Comment by timlinux** [comment]
confirmed it was stale parameters submodule....
