### ISSUE TITLE
Python Error: classifying cyclone hazard layer

### ISSUE THREAD

**Issue by wcarthur** [inasafe/inasafe#4021]
When initially selecting a classification for cyclone wind hazard, a TypeError is raised

```
TypeError: string indices must be integers, not str
Traceback (most recent call last):
  File "C:/Users/u12161/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_kw33_multi_classifications.py", line 1114, in classifications_combo_box_changed
    self.activate_classification(exposure, classification)
  File "C:/Users/u12161/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard\step_kw33_multi_classifications.py", line 1151, in activate_classification
    classification, selected_unit)
  File "C:/Users/u12161/.qgis2/python/plugins\inasafe\safe\definitions\utilities.py", line 357, in default_classification_thresholds
    min_value = hazard_class['numeric_default_min'][unit['key']]
TypeError: string indices must be integers, not str
```

Can close the dialog, edit thresholds and continue with Keyword creation.

### Environment
* InaSAFE : 4.0.0
* QGIS : 2.14.4
* OS : Windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : N/A
  * Hazard : NetCDF4 continuous raster data
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by Gustry** [comment]
Thanks for the report.
This has been fixed in the PR above. The patch is going to be included in 4.0.1 release.
