### ISSUE TITLE
AttributeError on assigning keywords for  aggregation layer

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#4068]
### Problem

When assigning keywords to an aggregation layer I encounter the following error:
```
An error has occurred while executing Python code: 

AttributeError: 'DefaultSelectParameterWidget' object has no attribute 'input' 
Traceback (most recent call last):
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard/wizard_dialog.py", line 664, in on_pbnNext_released
    new_step.set_widgets()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard/step_kw47_default_inasafe_fields.py", line 175, in set_widgets
    self.parameter_container.setup_ui()
  File "/home/admire/.qgis2/python/plugins/inasafe/safe_extras/parameters/qt_widgets/parameter_container.py", line 191, in setup_ui
    parameter_widget = self.qt4_parameter_factory.get_widget(parameter)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe_extras/parameters/qt_widgets/qt4_parameter_factory.py", line 73, in get_widget
    return self.dict_widget[class_name](parameter)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/common/parameters/default_select_parameter_widget.py", line 40, in __init__
    self.radio_button_enabler = self.input.itemData(0, Qt.UserRole)
AttributeError: 'DefaultSelectParameterWidget' object has no attribute 'input'


Python version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2] 
QGIS version: 2.14.3-Essen Essen, exported 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/admire/.qgis2/python
/home/admire/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/home/admire/.qgis2//python
/home/admire/.qgis2/python/plugins
/home/admire/.qgis2/python/plugins/inasafe
/home/admire/.qgis2/python/plugins/inasafe/safe_extras/parameters
/home/admire/.qgis2/python/plugins
/home/admire/.qgis2/python/plugins/inasafe/safe_extras
/usr/share/qgis/python/plugins/fTools/tools
```

### Expected Behaviour

Allow keywords to be assigned
### Environment
* InaSAFE :  dev
* QGIS :  2.14.3 and 2.18.3
* OS : Ubuntu
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure :  
  * Hazard : 
  * Aggregation : `aggregation/grid_jakarta_4326.geojson`
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ? Yes
  * If yes, where (BTSync, data.inasafe.org, zip) ? . Data is available in inasafe repo

### Proposed Solution
Make it happy

**Comment by myarjunar** [comment]
this is something with my changes, but unfortunately I can't replicate the issue.

**Comment by ismailsunni** [comment]
Closing this, I can't replicate the problem. The only explanation is we forget to run `git submodule update`. If you still got this problem, run`git submodule update` or re-open this ticket.
