### ISSUE TITLE
Not enough free memory to run Tsunami and Population Raster with Aggregation

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4106]
### Problem
Hi everyone, i briefly mentioned this on gitter the other day. 
Tsunami and Population Raster work fine together but with an aggregation, it gets a Memory issue

From the Inasafe Log
```
2017-04-21T15:06:06	0	aggregation: Convert the aggregation layer to the analysis layer
2017-04-21T15:06:06	0	Starting a GIS overlay analysis
2017-04-21T15:06:06	0	ANALYSIS : Hazard preparation
2017-04-21T15:06:06	0	hazard: use_same_projection: True
2017-04-21T15:06:06	0	hazard: Clip raster by analysis bounding box
2017-04-21T15:06:30	0	hazard: Classify continuous raster hazard
2017-04-21T15:09:11	0	The impact function could not run because of the inputs.
2017-04-21T15:09:12	0	****Memory issue
			
			There is not enough free memory to run this analysis.
```
From theProcessing Log
```
2017-04-21T15:03:34	2	Could not load provider: GRASS commands
			Traceback (most recent call last):
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\core\Processing.py", line 92, in addProvider
			    provider.initializeSettings()
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\algs\grass\GrassAlgorithmProvider.py", line 70, in initializeSettings
			    GrassUtils.grassHelpPath()))
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\algs\grass\GrassUtils.py", line 423, in grassHelpPath
			    localPath = os.path.join(Grass7Utils.grassPath(), 'docs/html')
			NameError: global name 'Grass7Utils' is not defined
			
2017-04-21T15:03:36	2	Problem with OTB installation: OTB was not found or is not correctly installed
2017-04-21T15:03:36	1	Specified SAGA folder does not exist. Will try to find built-in binaries.
2017-04-21T15:06:30	0	GDAL execution console output
			Input file size is 3122, 1456
			
			There is not enough free memory to run this analysis.
```

### Expected Behaviour
it runs!

### Environment
* InaSAFE : 4.0.0 
* QGIS : 2.18.3
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : [popmap15.tif](url)
  * Hazard : Flood.asc (Tsunami inundation)
  * Aggregation : TON_vid_3857
  * Extent :Intersection of datasets
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by lrpower** [comment]
[TsunamiPopulationRasterAgregationTest.zip](https://github.com/inasafe/inasafe/files/946069/TsunamiPopulationRasterAgregationTest.zip)

**Comment by timlinux** [comment]
Hi Tested here @lrpower and can replicate:

![qgis](https://cloud.githubusercontent.com/assets/178003/25278867/f1d99c8e-26a4-11e7-8d27-db0549951922.gif)

**Comment by timlinux** [comment]
@lrpower as a work around, select just the aggregation areas that coincide with the hazard dataset - I tried that and it used significantly less memory:

![qgis](https://cloud.githubusercontent.com/assets/178003/25280579/c1df35ce-26aa-11e7-9b25-8d55931638a4.gif)

I think we might have a memory leak or something - I will need to investigate further in the code.

The full analysis did run for me but I have 16gb ram in my computer - I suspect you have less?

**Comment by timlinux** [comment]
@lrpower just checking in here - I think I mentioned in bitter that it should run successfully if you just select the aggregation areas of the main area where the tsunami hit for now. I have added some profiling tools to see where the leaks are happening but I don't have an immediate fix for the underlying issue, so I suggest to use the 'selection of aggregation areas' as a work around for now.

**Comment by lrpower** [comment]
Hi @timlinux I have 8.0GB ram. (Geez i didn't realise how long ago i posted this - where has the time gone?)
I still have memory issues with this IF but selecting the village boundaries works. Thanks for that.
