### ISSUE TITLE
Blocking bug with the FR translation 

### ISSUE THREAD

**Issue by severinmenard** [inasafe/inasafe#4277]
Seems there is a typo in the FR translation that blocks the load of InaSAFE when starting QGIS. It provides the error msg below. Same blocking isue if you try to install InaSAFE from QGIS with locale set in French. It works fine if locale forced in US English

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 5: ordinal not in range(128) 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/severin/.qgis2/python/plugins/inasafe/__init__.py", line 86, in classFactory
    from safe.plugin import Plugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/__init__.py", line 28, in 
    from safe.common.custom_logging import setup_logger
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/__init__.py", line 28, in 
    from safe.common.custom_logging import setup_logger
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/common/custom_logging.py", line 31, in 
    from safe.common.utilities import log_file_path
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/common/utilities.py", line 25, in 
    from safe.utilities.rounding import (
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/utilities/rounding.py", line 6, in 
    from safe.definitions.units import unit_mapping
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/definitions/__init__.py", line 15, in 
    from safe.definitions.exposure import *
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/definitions/exposure.py", line 18, in 
    from safe.definitions.field_groups import population_field_groups
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/definitions/field_groups/__init__.py", line 4, in 
    from field_groups import *
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/severin/.qgis2/python/plugins/inasafe/safe/definitions/field_groups/field_groups.py", line 93, in 
    tr('Infant: {note}'.format(note=concepts['infant']['description'])),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 5: ordinal not in range(128)

Version de Python : 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] 
Version de QGIS : 2.14.5-Essen Essen, exported 

Chemin Python :
/usr/share/qgis/python
/home/severin/.qgis2/python
/home/severin/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/home/severin/.qgis2//python
/home/severin/.qgis2/python/plugins/mmqgis/forms
/home/severin/.qgis2/python/plugins/inasafe
/home/severin/.qgis2/python/plugins/inasafe/safe_extras/parameters
/home/severin/.qgis2/python/plugins
/home/severin/.qgis2/python/plugins/inasafe/safe_extras

**Comment by Gustry** [comment]
I installed InaSAFE yesterday on a computer in French. I didn't get any problem. I will have a look this afternoon.
Did you try to open a specific window?

**Comment by severinmenard** [comment]
Yesterday a full set of 6 trainees working on various systems (Ubuntu 16.04, EmmaBuntu and Win7) and QGIS 2.14 or 2.18 could not install InaSAFE, getting this error msg, except the only using QGIS in English. It was already installed on my Ubuntu 16.04 but with the mention that it was corrupted. Therefore I reinstalled it and got the same message than the trainees. Only solved it when I change the lovale for US English

**Comment by Gustry** [comment]
Ok thanks. I could notice another bug. On my computer, QGIS is in French but InaSAFE stays in English. That's why I didn't notice your bug. (I didn't notice Inasafe was in English despite French on QGIS).

**Comment by Gustry** [comment]
I couldn't replicate my bug where QGIS is in French but InaSAFE in English.
Anyway, I made a PR to fix your bug @severinmenard. Thanks. I will try to use InaSAFE in French more often. We will release 4.1.2 soon (before next weekend for sure)

**Comment by severinmenard** [comment]
I don't know if it is a bug, but I think you can have InaSAFE in French
only if you force the locale in French. If your OS is in French and you do
not force the locale, then you have QGIS in FR and InaSAFE in EN

Le 22 juin 2017 14:30, "Etienne Trimaille" <notifications@github.com> a
écrit :

**Comment by Gustry** [comment]
If this is true, this is a bug. InaSAFE (like every other plugins) should follow QGIS locale, whenever the language is forced or not forced in QGIS.

I just tried on a windows machine in French, now QGIS and InaSAFE are in French, without using a forced locale. So I can't replicate this bug anymore now. Please report the bug if InaSAFE is not following the QGIS locale.

**Comment by Gustry** [comment]
We released InaSAFE 4.1.2 this morning to fix this issue. Please try again and report any issue you encounter ;-)
