### ISSUE TITLE
Keywords wizard does not enable if layer keywords metadata error fails

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4284]
### Problem

When selecting a layer with no keywords in 4.1:

```
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/plugin.py", line 914, in layer_changed
    keywords = KeywordIO().read_keywords(layer)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 80, in read_keywords
    return read_iso19115_metadata(source, keyword)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/metadata.py", line 116, in read_iso19115_metadata
    raise MetadataReadError(message)
safe.common.exceptions.MetadataReadError: No keyword version found. Metadata xml file is invalid.
```

### Environment
* InaSAFE : 4.1
* QGIS : 2.14
* OS : Mac
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution

Add better exception handling

**Comment by Gustry** [comment]
Can we close this one @timlinux ?
