### ISSUE TITLE
Impact result from land cover vs flood raster with aggregation not complete polygon

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4352]
### Problem
When I try the analysis of land cover vs flood raster with aggregation, I get the impact result map is not in complete polygon. It is different when I run the analysis of land cover vs flood raster without aggregation, that show the complete polygon. 
![image](https://user-images.githubusercontent.com/13621886/29012552-a6463dd8-7b66-11e7-975c-87f99457ec36.png)
When I check the total number in each estimated area also have the same total number. It is strange, because in the general report, all of them show the `use caution` result in the same total number, whether supposedly if there is a missing shape area, then the `use caution' area at least have a smaller total number than the full of impact polygon result.

And when I run with debug mode, I get some error message 
```
Traceback (most recent call last):
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1215, in accept
    self.impact_function, self.iface)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gui\analysis_utilities.py", line 64, in generate_impact_report
    return impact_report.process_components()
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\impact_report.py", line 715, in process_components
    context = _extractor_method(self, component)
  File "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\report\extractors\analysis_detail.py", line 544, in analysis_detail_extractor
    total_count = int(float(feat[field_index]))
KeyError: '-1'
```

### Expected Behaviour
The analysis result IF of land cover vs flood raster with aggregation can show the best result, without missing area.

### Environment
* InaSAFE : 4.2.0b0 (Develop)
* QGIS : 2.14.14
* OS : Win-7 Pro/ 64-bit 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Jakarta_Landcover_WGS84.shp
  * Hazard : Jakarta_Flood_HKV_WGS84.tif
  * Aggregation : Jakarta_District_Boundary_WGS84.shp
  * Extent : 
  
Checklist (if applicable): 
* [x] Did you try to run it in debug mode ? Yes, no result and busy cursor
* [x] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? In Real World Data

### Proposed Solution
Make it happy

**Comment by Gustry** [comment]
Thanks for reporting the issue.
I'm going to have a look to the analysis itself with your data.
@myarjunar Can you have a look to the debug mode, it looks failing in the extractor.

**Comment by Gustry** [comment]
Even without debug mode
```
2017-08-10T08:37:58	0	Le rapport d'impact n'a pas pu être généré.
2017-08-10T08:37:58	0	****Problème de génération du rapport
			
			****Erreur pour extraire le contexte.
			
			****Problème
			
			    Les problèmes suivants sont survenus pendant le processus d'analyse.
			
			 - KeyError
			
			****Suggestion
			
			    Vous pouvez essayer ce qui suit pour résoudre le problème :
			
			 - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
			 - Check the InaSAFE documentation to see if you are trying to do something unsupported.
			 - Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
			 - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
			
			*****Détails
			
			    Ces détails supplémentaires ont été signalés lorsque le problème est survenu.
			
			 - -1
			
			*****Diagnostique
			
			 1. In file "/Users/etienne/.qgis2/python/plugins/inasafe/safe/report/impact_report.py", line 715, in process_components context = _extractor_method(self, component)
			 2. In file "/Users/etienne/.qgis2/python/plugins/inasafe/safe/report/extractors/analysis_detail.py", line 544, in analysis_detail_extractor total_count = int(float(feat[field_index]))
```
My hazard keywords
[Jakarta_Flood_HKV_WGS84.xml.zip](https://github.com/inasafe/inasafe/files/1213848/Jakarta_Flood_HKV_WGS84.xml.zip)

**Comment by felix-yew** [comment]
[Jakarta_Flood_Landcover_Aggregation_xml.zip](https://github.com/inasafe/inasafe/files/1213905/Jakarta_Flood_Landcover_Aggregation_xml.zip) --> all keyword

**Comment by myarjunar** [comment]
> Can you have a look to the debug mode, it looks failing in the extractor.

I can fix the extractor but it's not what causing some areas are missing.

**Comment by Gustry** [comment]
Yes, I'm looking the first part of this issue (some areas which are missing)

**Comment by Gustry** [comment]
Thanks @myarjunar It's working now for the reporting side.

But for the impact function, it's a problem with invalid geometries which are dropped when we intersect the exposure and the aggregate hazard. https://github.com/inasafe/inasafe/blob/develop/safe/impact_function/impact_function.py#L2040

Unfortunately, we are already cleaning geometries for both layers just before this algorithm. Looking what we can do inside this intersection algorithm.

**Comment by Gustry** [comment]
Both layers have invalid geometries before the intersection algorithm according to the geometry checker in QGIS.

**Comment by timlinux** [comment]
@Gustry lets plan to get @wonder-sk to help us with this.

**Comment by wonder-sk** [comment]
Having received test data from @Gustry, I am unable to reproduce the problem. It could be that I can't reproduce the problem because of different keywords for Jakarta_Flood_HKV_WGS84.tif. In my test data there are just two categories specified in the keywords (dry < 1m, wet > 1m) while in the screenshot in the bug report I can see multiple hazard categories (high, medium, low, use caution). This could cause that different polygons are created for analysis and thus different results are produced. Any hints how can I get equivalent keywords @Gustry ?

**Comment by wonder-sk** [comment]
I have been testing vector overlay operations in QGIS 3 using the fresh new ingredients:
- rewritten union/intersection/difference algorithms
  - https://github.com/qgis/QGIS/pull/6811
  - https://github.com/qgis/QGIS/pull/6853
  - https://github.com/qgis/QGIS/pull/6859
- rewritten snap geometries algorithm: https://github.com/qgis/QGIS/pull/7194

With the Jakarta flood + land use I was getting good results without any issues. The recommended way of running the analysis:
1. land use: run "snap geometries" alg followed by "fix geometries" alg
2. flood: convert raster to vector followed by "fix geometries" alg
3. run union on layers produced in steps 2 and 3.

Fixing of geometries runs equivalent of postgis' ST_MakeValid to fix geometries (much better than using buffer(0)).

It is recommended that "snap geometries" algorithm is run before fixing geometries. The land use polygon layer of Jakarta was producing topological errors in GEOS during union due to small differences between some coordinates of source geometries. Snapping coordinates with a small tolerance solved the numerical issues.
