### ISSUE TITLE
RFC: Going 'micro' for easy use of inasafe in other services

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#4356]
## Problem
The current setup in other services (InaSAFE Realtime and GeoSAFE) is not quite nice: For those 2 services, we use this branch: https://github.com/inasafe/inasafe-realtime/tree/realtime-backport-cherry-pick. This branch is basically an InaSAFE repository that still have realtime package. @lucernae has explained that InaSAFE team decided to remove the realtime package and since he was busy with the functionality of GeoSAFE, he didn't have time to revamp the architecture from the beginning. In GeoSAFE itself, this branch is a submodule. One of the drawbacks is that, whenever there is changes in InaSAFE, we have to also update it in that branch. 

Note that the master branch of inasafe-realtime repository submodules the inasafe repository (it's not used by any services), but it doesn't work since the dependency between packages is off there. We could continue this approach (with submodules) but we need to add python path in places as necessary.

## Proposed Solution
Another approach is to pip-package subpackages needed as preferred by @timlinux. I checked the dependencies between packages shipped in InaSAFE. The dependency is depicted as follows:
![safe dependencies](https://user-images.githubusercontent.com/992519/29120390-38978864-7d0a-11e7-8987-8227a8751b89.png)

Some efforts are needed to realize this:
### Restructuring inasafe-realtime
The work is still on progress here https://github.com/akbargumbira/inasafe-realtime/tree/develop. It still has some problems with safe_extras dependencies (since I haven't merged the work needed explained below).

### Packaging CLI
I moved the sub-package bin into its own repository here https://github.com/akbargumbira/inasafe_cli. This CLI has been rewritten too to work with InaSAFE 4.

### Packaging SAFE
The work is done in this PR https://github.com/inasafe/inasafe/pull/4343. If we see the diagram above safe requires safe_extras that contains 4 sub-packages: parameters, raven, pydispatch, simplejson.

Raven, pydispatch, and simplejson are available in pip, so we can install it from there. Another thing we need to do is to package parameters.

### Packaging Parameters
The work is done in this PR https://github.com/inasafe/parameters/pull/24. I have tried plugging in this package into inasafe (just by copying the package to safe_extras) and the plugin works fine.

There are some discussions in that PR that you might want to check. One of the problem is the inconsistency on how we import external libraries in SAFE package:

* raven used only in safe/common/custom_logging.py:
```
from raven.handlers.logging import SentryHandler
```

* pydispatcher:
```
from safe_extras.pydispatch import dispatcher
```

* simplejson used by raven imported this way:
```
import simplejson as json
```

* parameters impoted this way:
```
from safe_extras.parameters.select_parameter import SelectParameter
```

We can't have SAFE self-packaged and importing pydispatch and parameters that way. So another work is to update the importing in SAFE package.

### Update importing external libraries in SAFE
The work is done here https://github.com/inasafe/inasafe/pull/4354

### Removing headless and bin from InaSAFE repository
SInce both packages are not needed in that repository and we don't want to have duplicates (they are in inasafe-realtime), I deleted both packages in this PR https://github.com/inasafe/inasafe/pull/4355

### Safe_extras future
Now that they are all available to install from pip. I thought that for the plugin, it's best to list them in REQUIREMENTS.txt and install them to safe_extras subdirectory for a release or set up development environment. We can do that by:
```

**Comment by timlinux** [comment]
Thanks for this @akbargumbira 

> We can't have SAFE self-packaged and importing pydispatch and parameters that way. So another work is to update the importing in SAFE package.

Is this the only import that uses the safe_extras path for the import? If we switch to using packaged raven etc. we will need to figure out how to package for the desktop nicely. I saw the folks at boundless use a tool (paver I think) to fetch and bundle deps in their plugins - I wonder if they also use relative paths for the imports. If we can get rid of safe_extras out of the main InaSAFE package I would be very happy.

For naming packages, using ```inasafe-``` as a prefix would be good e.g.:

* inasafe-core
* inasafe-cli
* inasafe-realtime
etc.

Also currently sentry is down - I need to deploy a new instance but I think we should keep and reinstate this dependency - and track raven to match the deployed version of sentry we have.

**Comment by akbargumbira** [comment]
> Is this the only import that uses the safe_extras path for the import?
Yes I've changed the importing.

> If we switch to using packaged raven etc. we will need to figure out how to package for the desktop nicely. I saw the folks at boundless use a tool (paver I think) to fetch and bundle deps in their plugins - I wonder if they also use relative paths for the imports. If we can get rid of safe_extras out of the main InaSAFE package I would be very happy.

Agreed. But I will put it as low priority (using paver for release/development setup)

Another blocker I have right now is about versioning. So I am trying to render map in realtime project and I have this error:
```
Error
Traceback (most recent call last):
  File "/home/akbar/dev/python/inasafe-realtime/src/realtime/test/test_shake_event.py", line 457, in test_render_map
    shake_event.render_map()
  File "/home/akbar/dev/python/inasafe-realtime/src/realtime/earthquake/shake_event.py", line 1388, in render_map
    _, impacts_html_path = self.calculate_impacts()
  File "/home/akbar/dev/python/inasafe-realtime/src/realtime/earthquake/shake_event.py", line 1094, in calculate_impacts
    function = ImpactFunction()
  File "/home/akbar/dev/python/inasafe-realtime/venv/local/lib/python2.7/site-packages/safe/impact_function/impact_function.py", line 272, in __init__
    self._provenance, provenance_inasafe_version, get_version())
  File "/home/akbar/dev/python/inasafe-realtime/venv/local/lib/python2.7/site-packages/safe/common/version.py", line 72, in get_version
    fid = open(os.path.join(root_dir, 'metadata.txt'))
IOError: [Errno 2] No such file or directory: '/home/akbar/dev/python/inasafe-realtime/venv/local/lib/python2.7/site-packages/metadata.txt'
```
The problem is that metadata.txt is on the same level as safe package (which is needed for the plugin). And I remembered that we removed ```__version__```` attribute from all the python modules. Right now function ```get_version``` retrieves the version from metadata file. So what do you think? @timlinux @ismailsunni @Gustry @lucernae?

**Comment by akbargumbira** [comment]
See here for the standard header discussion: https://github.com/inasafe/inasafe/issues/129
