### ISSUE TITLE
Error when printing for layer loaded in project

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4619]
### Problem

I did these steps:

1. run an analysis
2. save the project
3. close QGIS
4. open QGIS and the project
5. try to print to PDF (I used a custom template but I think even for the defaults it will replicate)
6. get a python error as listed below:

```
An error has occurred while executing Python code: 

AttributeError: 'QgsVectorLayer' object has no attribute 'keywords' 
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/print_report_dialog.py", line 387, in accept
    generated_components, iface=self.iface)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 2888, in generate_report
    extra_layers=extra_layers)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/report/impact_report.py", line 312, in __init__
    impact or self._impact_function.impact)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 619, in impact
    return self._outputs()[0]
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 598, in _outputs
    purpose = layer.keywords.get('layer_purpose')
AttributeError: 'QgsVectorLayer' object has no attribute 'keywords'


Python version: 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] 
QGIS version: 2.18.13 Las Palmas, exported 

Python Path:
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/timlinux/.qgis2/python
/Users/timlinux/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg
/Library/Python/2.7/site-packages/pycharm-debug.egg
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Users/timlinux/Library/Python/2.7/lib/python/site-packages
/usr/local/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages/pycharm-debug.egg
/usr/local/lib/python2.7/site-packages/geos
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/timlinux/.qgis2//python
/Users/timlinux/.qgis2/python/plugins/cadasta-qgis-plugin
/Users/timlinux/.qgis2/python/plugins/cadasta-qgis-plugin/safe_extras
/Users/timlinux/.qgis2/python/plugins/qgis_resource_sharing
/Users/timlinux/.qgis2/python/plugins/qgis_resource_sharing/ext_libs
/Users/timlinux/.qgis2/python/plugins/inasafe
/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras/parameters
/Users/timlinux/.qgis2/python/plugins
/Users/timlinux/.qgis2/python/plugins/inasafe/safe_extras
.
/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools
/Users/timlinux/gisdata/InaSAFE/Jakarta
```

### Environment
* InaSAFE : develop / 4.3
* QGIS : 2.18
* OS : MacOS
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by Gustry** [comment]
Fixed in PR
