### ISSUE TITLE
Key words missing: set analysis area

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4652]
## problem ##
When I set the analysis area by selecting an area on the map #4650 and run analysis on a single exposure layer; the resulting impact layer is not printable. The dock shows a message saying the "layer keywords missing:" The print option is greyed out regardless of which element in the output folder I click on.

## proposed solution ##
analysis with selected area on the map canvas should produce results that are printable.

**Comment by Gustry** [comment]
Do you mean when you run the analysis from the dock or impact function wizard, you have the message "Layer keywords missing?

**Comment by Charlotte-Morgan** [comment]
Yes

**Comment by Gustry** [comment]
I still couldn't replicate the issue.
@myarjunar Any idea if a recent change in the dock might be the source of this issue?

**Comment by myarjunar** [comment]
hm maybe this issue appears before we merge our fix for no keywords error #4658 #4653

**Comment by Charlotte-Morgan** [comment]
hi @Gustry  and @myarjunar i have tried again and the problem is still there.

![image](https://user-images.githubusercontent.com/5743135/33155043-178fb968-d041-11e7-8fe9-b5d3a4d33114.png)
I am using windows 7, QGIS 2.18.14 and InaSAFE dev with standard Maumere tsunami and OSM buildings data

**Comment by myarjunar** [comment]
@Charlotte-Morgan so there is no error message in the log messages panel? could you give me all the results in the analysis directory? that would help,, thanks

**Comment by ivanbusthomi** [comment]
@myarjunar and @Gustry 
I encountered the same behaviour too
this is my log message
```
2017-11-23T17:29:39	0	Sentry logging disabled in safe
2017-11-23T17:29:39	0	Sentry logging disabled in safe
2017-11-23T17:30:28	0	ANALYSIS : The impact function is starting.
2017-11-23T17:30:28	0	Datastore : D:/temp/__inasafe_temp_result/TsunamiRasterOnRoadsLine_23November2017_17h30-28.456000
2017-11-23T17:30:28	0	ANALYSIS : Pre processing
2017-11-23T17:30:28	0	ANALYSIS : Aggregation preparation
2017-11-23T17:30:28	0	aggregation: provided: False
2017-11-23T17:30:28	0	The aggregation layer is not provided. We are going to create it from the analysis extent and the expected CRS.
2017-11-23T17:30:28	0	impact function: crs: EPSG:4326
2017-11-23T17:30:28	0	aggregation: Convert bbox aggregation to polygon layer with keywords
2017-11-23T17:30:28	0	The exposure is a vector layer. According to the kind of exposure, we need to check if the exposure has some counts before adding some default ratios.
2017-11-23T17:30:28	0	aggregation: Convert the aggregation layer to the analysis layer
2017-11-23T17:30:28	0	ANALYSIS : Hazard preparation
2017-11-23T17:30:28	0	hazard: use_same_projection_as_aggregation: True
2017-11-23T17:30:28	0	hazard: Clip raster by analysis bounding box
2017-11-23T17:30:28	0	hazard: Classify continuous raster hazard
2017-11-23T17:30:28	0	hazard: Polygonize classified raster hazard
2017-11-23T17:30:28	0	hazard: Clip and mask hazard polygons with the analysis layer
2017-11-23T17:30:28	0	hazard: Cleaning the vector hazard attribute table
2017-11-23T17:30:28	0	Features which have been removed from hazard : 0
2017-11-23T17:30:28	0	We add an ID column in hazard
2017-11-23T17:30:28	0	Fields which have been removed from hazard : hazard_val
2017-11-23T17:30:28	0	hazard: Assign classes based on value map
2017-11-23T17:30:28	0	ANALYSIS : Aggregate hazard preparation
2017-11-23T17:30:28	0	hazard: Make hazard layer valid
2017-11-23T17:30:28	0	aggregation: Union hazard polygons with aggregation areas and assign hazard class
2017-11-23T17:30:28	0	ANALYSIS : Exposure preparation
2017-11-23T17:30:28	0	exposure: use_same_projection_as_aggregation: True
2017-11-23T17:30:28	0	exposure: Smart clip
2017-11-23T17:30:28	0	exposure: Cleaning the vector exposure attribute table
2017-11-23T17:30:28	0	Features which have been removed from exposure : 0
2017-11-23T17:30:28	0	We add an ID column in exposure
2017-11-23T17:30:28	0	Fields which have been removed from exposure : NAME OSM_TYPE TYPE
2017-11-23T17:30:28	0	exposure: Compute ratios from counts
2017-11-23T17:30:28	0	Population count field population_count_field is not detected in the exposure. We will not compute a ratio from this field because the formula needs Population count field. Formula: ratio = subset count / total count.
2017-11-23T17:30:28	0	exposure: Clip the exposure layer with the analysis layer
2017-11-23T17:30:29	0	exposure: Add default values
2017-11-23T17:30:29	0	inasafe_default_value is not present, we can not fill default ratios for this layer.
2017-11-23T17:30:29	0	exposure: Assign classes based on value map
2017-11-23T17:30:29	0	ANALYSIS : Intersect Exposure and Aggregate Hazard
2017-11-23T17:30:29	0	exposure: Make exposure layer valid
2017-11-23T17:30:29	0	impact function: Make aggregate hazard layer valid
2017-11-23T17:30:29	0	impact function: Intersect divisible features with the aggregate hazard
2017-11-23T17:30:29	0	ANALYSIS : Post processing
2017-11-23T17:30:29	0	The size calculator is set to use Meters
2017-11-23T17:30:29	0	post_processor: Size Value Post Processor
2017-11-23T17:30:29	0	Size Value Post Processor : Running
2017-11-23T17:30:29	0	post_processor: Affected Post Processor
2017-11-23T17:30:29	0	Affected Post Processor : Running
2017-11-23T17:30:29	0	ANALYSIS : Summary calculation
2017-11-23T17:30:29	0	impact function: Aggregate the impact summary
2017-11-23T17:30:29	0	Computing the aggregate hazard summary.
2017-11-23T17:30:29	0	impact function: Aggregate the aggregation summary
2017-11-23T17:30:29	0	impact function: Aggregate the analysis summary
2017-11-23T17:30:29	0	impact function: Build the exposure summary table
2017-11-23T17:30:29	0	Layer saved impact_analysis
2017-11-23T17:30:29	0	Layer saved hazard_aggregation_summary
2017-11-23T17:30:29	0	Layer saved exposure_summary_table
2017-11-23T17:30:29	0	Layer saved aggregation_summary
2017-11-23T17:30:29	0	Layer saved analysis_summary
2017-11-23T17:30:29	0	Layer saved Analysis Log
2017-11-23T17:30:29	0	ANALYSIS : Styling
2017-11-23T17:30:29	0	Aggregation None
2017-11-23T17:30:29	0	The impact function could run without errors.
2017-11-23T17:30:31	0	Showing No Keywords Message
2017-11-23T17:30:31	0	Showing No Keywords Message
2017-11-23T17:30:31	0	Showing No Keywords Message
2017-11-23T17:30:32	0	Showing No Keywords Message
2017-11-23T17:30:32	0	InaSAFE Impact Report class initialised
2017-11-23T17:30:32	0	Showing No Keywords Message
2017-11-23T17:30:32	0	Showing No Keywords Message
2017-11-23T17:30:33	0	Showing No Keywords Message
2017-11-23T17:30:38	0	Showing No Keywords Message
2017-11-23T17:30:39	0	Showing No Keywords Message
2017-11-23T17:30:40	0	Showing No Keywords Message
2017-11-23T17:30:41	0	Showing No Keywords Message
```

**Comment by myarjunar** [comment]
@ivanbusthomi could you give me all the results in the analysis directory? maybe on zip, thanks

**Comment by ivanbusthomi** [comment]
here it is @myarjunar 
[TsunamiRasterOnPopulationRaster_23November2017_17h52-18.608000.zip](https://github.com/inasafe/inasafe/files/1498744/TsunamiRasterOnPopulationRaster_23November2017_17h52-18.608000.zip)

**Comment by myarjunar** [comment]
What if you run the multiexposure @ivanbusthomi  @Charlotte-Morgan ? does it also show no keywords message?

**Comment by Gustry** [comment]
Can you try my PR #4682 to see what is the error message @ivanbusthomi or @Charlotte-Morgan ?

@ismailsunni @myarjunar I suspect this `try ... catch` to be too broad and the `AttributeError` is hiding something from us. That's it's bad to have this kind of try catch in the code at very high level of code (ie in the dock)
https://github.com/inasafe/inasafe/blob/develop/safe/gui/widgets/dock.py#L776

**Comment by Charlotte-Morgan** [comment]
done

**Comment by Charlotte-Morgan** [comment]
@myarjunar - when i test #4681 with multiple exposure I get the followign python error in a popup
```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'isGeosValid' 
Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 713, in get_layers
    self.layer_changed(self.iface.activeLayer())
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 940, in layer_changed
    keywords))
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2689, in load_from_output_metadata
    requested_extent)
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\gis.py", line 312, in wkt_to_rectangle
    if not geometry.isGeosValid():
AttributeError: 'NoneType' object has no attribute 'isGeosValid'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.14 Las Palmas, ff83b9a479 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/AIFDR_ADMIN/.qgis2/python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\Program Files (x86)\ArcGIS\Desktop10.2\bin
C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy
C:\Program Files (x86)\ArcGIS\Desktop10.2\ArcToolbox
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/AIFDR_ADMIN/.qgis2//python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras
C:/AIFDR II - SDA/10_InaSAFE Analysis/20171121 Maumere 4.3
```
![image](https://user-images.githubusercontent.com/5743135/33189276-4cf6e3ce-d0f5-11e7-8e83-c99e241f463c.png)

BTW - I can not close this window :) or save or ... do anything but crash out

**Comment by myarjunar** [comment]
thanks @Charlotte-Morgan , really helps me to know what the problem is

**Comment by Gustry** [comment]
Can you try again with the latest develop @Charlotte-Morgan and @ivanbusthomi ?

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry and @myarjunar 
I am testing in the dock - tsunami and buildings. It runs fine, analysis is limited to the selected area and there are no errors in the dock about missing key words. Results are in the dock but print button is not active. A result folder exists on disc with these files.
![image](https://user-images.githubusercontent.com/5743135/33245322-39b1faa8-d35a-11e7-8bf0-623722a7751c.png)

**Comment by Gustry** [comment]
I guess this ticket is fixed.
Also related to #4695 

Feel free to reopen if needed
