### ISSUE TITLE
Python error: load test data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4701]
## problem ##
Unable to load test data.

## environment ##
Windows, QGIS 2.18, InaSAFE dev, sun shining, tongue in mouth ...

## error message ##
```
2017-11-30T12:44:24	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\plugin.py", line 693, in add_test_layers
			    from safe.test.utilities import load_standard_layers
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\test\utilities.py", line 8, in <module>
			    import mock
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\mock\__init__.py", line 2, in <module>
			    import mock.mock as _mock
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\mock\mock.py", line 69, in <module>
			    from pbr.version import VersionInfo
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pbr\version.py", line 25, in <module>
			    import pkg_resources
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named pkg_resources
			
2017-11-30T12:44:29	1	Traceback (most recent call last):
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\plugin.py", line 693, in add_test_layers
			    from safe.test.utilities import load_standard_layers
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\test\utilities.py", line 8, in <module>
			    import mock
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\mock\__init__.py", line 2, in <module>
			    import mock.mock as _mock
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\mock\mock.py", line 69, in <module>
			    from pbr.version import VersionInfo
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pbr\version.py", line 25, in <module>
			    import pkg_resources
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named pkg_resources
			
```

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 

It seems we need a python module to load the test data. It's called `mock`. You can do it by run this command in command prompt:
```
pip install mock
```

If it said you don't have `pip`, you can follow this instruction here: https://pip.pypa.io/en/stable/installing/#do-i-need-to-install-pip to get the `pip` installed. Try to install `mock` again like above.

Yes, it's not a user friendly feature, since it's intended to be used for developer.

Let me know if you need a help.

I can replicate your problem if I don't have `mock` installed in MacOS, although different error message.

**Comment by Gustry** [comment]
I made the PR above so you can click the button without `mock` on your computer ;-)

**Comment by Charlotte-Morgan** [comment]
aw - thankyou. :) i was going to just go and grab the data manually from the repo

**Comment by ismailsunni** [comment]
Thanks @Gustry , it works now.
