### ISSUE TITLE
Exception when we open the template in the composer on Windows

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#4713]
### Problem

I get that trying to open the template after running flood on buildings on windows
```
An error has occurred while executing Python code: 

TypeError: 'NoneType' object has no attribute '__getitem__' 
Traceback (most recent call last):
  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\gui\tools\print_report_dialog.py", line 402, in accept
    map_report, self.selected_template_path)]
  File "C:/Users/Tim/.qgis2/python/plugins\inasafe\safe\definitions\utilities.py", line 504, in override_component_template
    template_directory, template_filename = split(template_path)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\ntpath.py", line 170, in split
    d, p = splitdrive(p)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\ntpath.py", line 125, in splitdrive
    if p[1:2] == ':':
TypeError: 'NoneType' object has no attribute '__getitem__'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.14 Las Palmas, ff83b9a479
```

Issue from @timlinux on Windows

**Comment by Gustry** [comment]
Is it fixed? You couldn't replicate?

**Comment by myarjunar** [comment]
ups my bad, I thought it was another ticket. but yes, I couldn't replicate this. and looking to the current code, it will not give `None` value. https://github.com/inasafe/inasafe/blob/develop/safe/gui/tools/print_report_dialog.py#L519

**Comment by Gustry** [comment]
so the `template_path` is never None you mean?
i checked quickly in the code, it seems it's not possible anymore as you are checking if the template exists on disk first.

@timlinux Can you replicate?
