### ISSUE TITLE
installation error: "ImportError: cannot import name QtWebKit"

### ISSUE THREAD

**Issue by lrntct** [inasafe/inasafe#5010]
### Problem

When I try to install inasafe from the QGIS plugin interface, I get the following error:

```
Couldn't load plugin inasafe due to an error when calling its initGui() method 

ImportError: cannot import name QtWebKit 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/plugin.py", line 569, in initGui
    self._create_dock()
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/plugin.py", line 544, in _create_dock
    from safe.gui.widgets.dock import Dock
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 90, in 
    from safe.gui.tools.help_dialog import HelpDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/gui/tools/help_dialog.py", line 14, in 
    FORM_CLASS = get_ui_class('help_dialog_base.ui')
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/utilities/resources.py", line 125, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 40, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/gui/widgets/message_viewer.py", line 25, in 
    from PyQt4 import QtCore, QtGui, QtWebKit
ImportError: cannot import name QtWebKit


Python version: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0] 
QGIS version: 2.18.17 Las Palmas, exported 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/laurent/.qgis2/python
/home/laurent/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/laurent/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk3
/home/laurent/.qgis2//python
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins/inasafe/safe_extras/parameters
/home/laurent/.qgis2/python/plugins
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins
/home/laurent/.qgis2/python/plugins/inasafe/safe_extras
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins
```

### Environment
* InaSAFE : 4.4.0
* QGIS : 2.18.17
* OS : Ubuntu 18.04

### Proposed Solution
I might be related to the deprecation of Qt4 from Debian/Ubuntu:
https://stackoverflow.com/questions/37604532/python-2-7-11-importerror-cannot-import-name-qtwebkit-kali-linux-debian-8
https://lists.debian.org/debian-devel-announce/2015/05/msg00001.html

**Comment by nyalldawson** [comment]
This is already fixed upstream in qgis

**Comment by timlinux** [comment]
Could you try the latest release of QGIS LTR from http://download.qgis.org @lrntct ?

**Comment by lrntct** [comment]
@timlinux I get the same error with QGIS 2.18.20 from ubuntugis (which is the recommended source from qgis.org):

```
Couldn't load plugin inasafe due to an error when calling its initGui() method 

ImportError: cannot import name QtWebKit 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/plugin.py", line 569, in initGui
    self._create_dock()
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/plugin.py", line 544, in _create_dock
    from safe.gui.widgets.dock import Dock
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 90, in 
    from safe.gui.tools.help_dialog import HelpDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/gui/tools/help_dialog.py", line 14, in 
    FORM_CLASS = get_ui_class('help_dialog_base.ui')
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/utilities/resources.py", line 125, in get_ui_class
    return uic.loadUiType(ui_file_path)[0]
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 211, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 40, in 
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/laurent/.qgis2/python/plugins/inasafe/safe/gui/widgets/message_viewer.py", line 25, in 
    from PyQt4 import QtCore, QtGui, QtWebKit
ImportError: cannot import name QtWebKit


Python version: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0] 
QGIS version: 2.18.20 Las Palmas, exported 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/laurent/.qgis2/python
/home/laurent/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/laurent/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk3
/home/laurent/.qgis2//python
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins/inasafe/safe_extras/parameters
/home/laurent/.qgis2/python/plugins
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins
/home/laurent/.qgis2/python/plugins/inasafe/safe_extras
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins
/home/laurent/.qgis2/python/plugins/inasafe
/home/laurent/.qgis2/python/plugins
```
