### ISSUE TITLE
Future imports do not work on MacOS

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#5051]
### Problem

When trying to install InaSAFE 5 on Mac OS Mojave it fails because of the future imports
```
Couldn't load plugin 'inasafe' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'future' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/__init__.py", line 89, in classFactory
    from .safe.plugin import Plugin
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/__init__.py", line 29, in 
    from safe.common.custom_logging import setup_logger
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/__init__.py", line 29, in 
    from safe.common.custom_logging import setup_logger
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/common/custom_logging.py", line 35, in 
    from safe.common.utilities import log_file_path  # NOQA
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/common/utilities.py", line 25, in 
    from safe.common.exceptions import VerificationError
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/common/exceptions.py", line 17, in 
    from safe.messaging.item.message_element import MessageElement
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/messaging/__init__.py", line 24, in 
    from .error_message import ErrorMessage
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/messaging/error_message.py", line 31, in 
    from .styles import (
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/messaging/styles.py", line 25, in 
    from future import standard_library
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'future'


Python version: 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS version: 3.4.1-Madeira Madeira, exported 

Python Path:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/admire/Library/Application Support/QGIS/QGIS3/profiles/default/python
```

### Expected Behaviour
Install properly on Mac OS
### Environment
* InaSAFE : 5.0
* QGIS : 3.4.1
* OS :  Mac OS Mojave

### Proposed Solution
Remove future imports

**Comment by NyakudyaA** [comment]
Installed it natively and it worked

**Comment by Gustry** [comment]
Yes it works but it's not supposed to be installed manually. InaSAFE shouldn't use this library
