### ISSUE TITLE
Cannot open map template in report

### ISSUE THREAD

**Issue by wcarthur** [inasafe/inasafe#5061]
### Problem

```
TypeError: setText(self, str): argument 1 has unexpected type 'tuple' 
Traceback (most recent call last):
  File "C:/Users/u12161/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\tools\print_report_dialog.py", line 557, in template_chooser_clicked
    self.template_path.setText(file_name)
TypeError: setText(self, str): argument 1 has unexpected type 'tuple'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.3-Madeira Madeira, 2f64a3c4e7 

```

```
2019-04-24T09:35:49     INFO    ****Report Generation issue
             
             ****Failed to extract context
             
             ****Problem
             
              The following problem(s) were encountered whilst running the analysis.
             
              - AttributeError
             
             ****Suggestion
             
              You can try the following to resolve the issue:
             
              - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
              - Check the InaSAFE documentation to see if you are trying to do something unsupported.
              - Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
              - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
             
             *****Details
             
              These additional details were reported when the problem occurred.
             
              - 'NoneType' object has no attribute 'authid'
             
             *****Diagnostics
             
              1. In file "C:/Users/u12161/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\report\impact_report.py", line 778, in process_components context = _extractor_method(self, component)
              2. In file "C:/Users/u12161/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\report\extractors\composer.py", line 433, in qgis_composer_extractor crs=impact_report.impact_function.crs.authid())
             
             
             ****Failed to extract context
             
             ****Problem
             
              The following problem(s) were encountered whilst running the analysis.
             
              - AttributeError
             
             ****Suggestion
             
              You can try the following to resolve the issue:
             
              - Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
              - Check the InaSAFE documentation to see if you are trying to do something unsupported.
              - Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
              - Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
             
             *****Details
             
              These additional details were reported when the problem occurred.
             
              - 'NoneType' object has no attribute 'authid'
             
             *****Diagnostics
             
              1. In file "C:/Users/u12161/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\report\impact_report.py", line 778, in process_components context = _extractor_method(self, component)
              2. In file "C:/Users/u12161/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\report\extractors\composer.py", line 433, in qgis_composer_extractor crs=impact_report.impact_function.crs.authid())
```

### Environment
* InaSAFE : 5.0.0
* QGIS : 3.4.3
* OS : Windows 7 enterprise

* Data used :
  * Exposure : Point data
  * Hazard : Cyclone (raster)
  * Aggregation : None
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ? No
* [ ] Is the data available ? No
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by carnendil** [comment]
### Problem

Same problem observed after following the InaSAFE lessons at https://changelog.inasafe.org/en/inasafe/lesson/advanced-inasafe-customisation/detail/127/?q=5.3 and trying to load the template thus created.

Error message:

```
TypeError: setText(self, str): argument 1 has unexpected type 'tuple' 
Traceback (most recent call last):
  File "C:\Users/Rainer.Parrales/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\tools\print_report_dialog.py", line 557, in template_chooser_clicked
    self.template_path.setText(file_name)
TypeError: setText(self, str): argument 1 has unexpected type 'tuple'


Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.22.11-Białowieża Białowieża, 106d33d7 
```

### Expected Behavior

Loading and using the template without error.

### Environment

 - InaSAFE : 5.0.5
 - QGIS : 3.22.11
 - OS : Windows 10 Version 2009
 - Data used:
   - Exposure : worldpop_25 (raster)
   - Hazard : tandale_floods (vector)
   - Aggregation : wards (vector)
   - Extent :

Checklist:
- [ ] Did you try to run it in debug mode ? No
- [x] Is the data available ? Yes: https://changelog.inasafe.org/en/inasafe/lesson/advanced-inasafe-customisation/zip/127/?q=5.3
