### ISSUE TITLE
shakemap converter Error

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#5062]
### Problem
Shakemap converter can not working properly.
This is the error message that i've got.
```
An error has occurred while executing Python code: 

safe.common.exceptions.InvalidLayerError 
Traceback (most recent call last):
  File "C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\tools\shake_grid\shakemap_converter_dialog.py", line 281, in accept
    extra_keywords=extra_keywords
  File "C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 1065, in convert_mmi_data
    return converter.mmi_to_raster(force_flag=True, algorithm=algorithm)
  File "C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 642, in mmi_to_raster
    self.create_keyword_file(algorithm)
  File "C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\tools\shake_grid\shake_grid.py", line 954, in create_keyword_file
    raise InvalidLayerError()
safe.common.exceptions.InvalidLayerError


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.6-Madeira Madeira, cc0e375a9f 

Python Path:
C:/PROGRA~1/QGIS 3.4/apps/qgis-ltr/./python
C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS 3.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS 3.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS 3.4\apps\Python37
C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\UNFPA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:/Users/UNFPA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe
C:\Users\UNFPA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\inasafe\safe_extras\parameters
C:\Users\UNFPA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\UNFPA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\inasafe\safe_extras
C:\Users\UNFPA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
```

### Environment
* InaSAFE : 5.0.0
* QGIS : 3.4
* OS : Win 10

* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by ismailsunni** [comment]
@samnawi can you share the file? It seems layer's related

**Comment by samnawi** [comment]
do you mean the xml file @ismailsunni ?
I use the xml file, downloaded from realtime.inasafe.go.id

**Comment by samnawi** [comment]
@ismailsunni the shakemap converter is working properly when I use the old version of QGIS 3.4 (my other laptop using 3.4.1)  but when I upgrade this laptop into 3.4.9, the shakemap converter didn't work.

**Comment by lucernae** [comment]
This is old issue, but probably related with #5063 ?
If #5063 is fixed, maybe we can fix this too.

**Comment by lucernae** [comment]
Fixed
