### ISSUE TITLE
Couldn't load InaSAFE 5.0.1 in Qgis 3.16.5

### ISSUE THREAD

**Issue by Sheepnok** [inasafe/inasafe#5089]
This problem was found after I updated the QGIS version from 3.16.0 to 3.16.5. This window was displayed when I started the program.

**Problem**

Couldn't load plugin 'inasafe' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'ogr' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/__init__.py", line 89, in classFactory
    from .safe.plugin import Plugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/plugin.py", line 33, in 
    from safe.utilities.expressions import qgis_expressions
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/expressions.py", line 8, in 
    from safe.report.expressions import infographic, map_report, html_report
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/report/expressions/html_report.py", line 24, in 
    from safe.definitions.reports.components import (
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/definitions/reports/components.py", line 47, in 
    from safe.report.extractors.aggregate_postprocessors import (
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/report/extractors/aggregate_postprocessors.py", line 23, in 
    from safe.processors.population_post_processors import (
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/processors/__init__.py", line 9, in 
    from safe.processors.pre_processors import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/processors/pre_processors.py", line 17, in 
    from safe.gis.raster.contour import create_smooth_contour
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gis/raster/contour.py", line 37, in 
    from safe.gis.vector.tools import (
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nokyoong/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gis/vector/tools.py", line 9, in 
    import ogr
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ogr'

### Environment
* InaSAFE : 5.0.1
* QGIS : 3.16.5
* OS : macoS

**Comment by abdulhafidz6** [comment]
Hi, this solution is worked in my side.

1. Open setting from QGIS menu bar > Options 
2. Click system tab > press the drop down arrow under Environment submenu
3. Add new variable by pressing the + button
4. Under Apply column, select If undefined
5. Variable : PYTHONPATH
6. Value : C:\OSGeo4W64\apps\Python37\Scripts;C:\Users\hp\AppData\Local\Programs\Python\Python37\Lib\site-packages
(it depends on your QGIS installation, it should be directed to the folder with "gdal_")

**Comment by lucernae** [comment]
Hi @abdulhafidz6, sorry for the late reply. This is indeed an issue and I can only confirm it after finally having a mac to test for.

The root cause is that some GDAL python lib version have module `ogr` as an alias to `from osgeo import ogr` (prior to GDAL 3.1). But in the mac version that alias don't exists (because it's using GDAL 3.1 above). Solution would be to fix our code to import the `from osgeo import ogr` like what's recommended in the official GDAL cookbook https://pypi.org/project/GDAL/.
