### ISSUE TITLE
ModuleNotFoundError: No module named 'imp' 

### ISSUE THREAD

**Issue by cablon** [inasafe/inasafe#5130]
### Problem
In QGIS 3.34 error ModuleNotFoundError: No module named 'imp' 
```
Copy/paste some InaSAFE logs here if it was an error.
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/ USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\plugin.py", line 563, in initGui
    self._create_dock()
  File "C:\Users/ USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\plugin.py", line 538, in _create_dock
    from safe.gui.widgets.dock import Dock
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\widgets\dock.py", line 90, in 
    from safe.gui.analysis_utilities import (
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\analysis_utilities.py", line 13, in 
    from safe.impact_function.impact_function_utilities import FROM_CANVAS
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\impact_function_utilities.py", line 20, in 
    from safe.report.impact_report import ImpactReport
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/ USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\report\impact_report.py", line 10, in 
    import imp
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'


<!---
Logs in QGIS are available in the bottom right corner on the bubble icon.
Then open the InaSAFE tab and copy/paste some logs.
-->

### Expected Behaviour

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
<!---
Filenames and paths so as to reproduce locally, a project is better.
It's nice if you can provide a ZIP with data in the ticket (drag and drop your zip on this textbox).
-->
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: <!--- if applicable -->
<!---
Replace the space between square brackets by a `x` to make it checked.
By running the analysis in debug mode, you may have some different errors.
-->
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution

**Comment by cablon** [comment]
[2024-05-28T201055     CRITICAL    T.txt](https://github.com/inasafe/inasafe/files/15469464/2024-05-28T201055.CRITICAL.T.txt)

**Comment by devinjohnson1986** [comment]
Has this been resolved yet? I'm having the same issue. Can you help? 
![image](https://github.com/user-attachments/assets/b871bca9-8ffc-4d27-8d55-59da8c57dcb0)

**Comment by isaiahlg** [comment]
Me and 3 colleagues are getting the same issue. Any updates? We noticed it only happens on Windows, not Mac with QGIS 3.34.

**Comment by qumleap** [comment]
I just installed the InaSAFE plugin version 5.0.6 and I am getting the same error message.  I am using Window 11 pro and QGIS 

I just started to use QGIS and I think is an awesome product. 


QGIS version
3.34.15-Prizren
QGIS code revision
386f2583
Qt version
5.15.13
Python version
3.12.8
GDAL/OGR version
3.10.1
PROJ version
9.5.1
EPSG Registry database version
v11.022 (2024-11-05)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.3
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009




Active Python plugins
HCMGIS
25.1.9
HouseNumbering3
version 0.0.5
QuickOSM
2.3.2
quick_map_services
0.20.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99









I just uploaded the InaSafe plugin Version 5.0.6 and I am getting the same error message. I am using Windows 11 pro. 

Couldn't load plugin 'inasafe' due to an error when calling its initGui() method 

ModuleNotFoundError: No module named 'imp' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\plugin.py", line 563, in initGui
    self._create_dock()
  File "C:\Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\plugin.py", line 538, in _create_dock
    from safe.gui.widgets.dock import Dock
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\widgets\dock.py", line 90, in 
    from safe.gui.analysis_utilities import (
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\gui\analysis_utilities.py", line 13, in 
    from safe.impact_function.impact_function_utilities import FROM_CANVAS
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\impact_function_utilities.py", line 20, in 
    from safe.report.impact_report import ImpactReport
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\report\impact_report.py", line 10, in 
    import imp
  File "C:\PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'


Python version: 3.12.8 (main, Dec 20 2024, 15:21:15) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.15-Prizren Prizren, 386f2583 

Python Path:
C:/PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python
C:/Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.15/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.15\apps\grass\grass84\etc\python
C:\Users\sjmm3\Documents
C:\Program Files\QGIS 3.34.15\bin\python312.zip
C:\PROGRA~1\QGIS33~1.15\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib
C:\Program Files\QGIS 3.34.15\bin
C:\PROGRA~1\QGIS33~1.15\apps\Python312
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.15\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/sjmm3/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\sjmm3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\sjmm3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HouseNumbering3/forms
C:/Users/sjmm3/OneDrive/Documents/New folder
C:\Users\sjmm3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\inasafe\safe_extras\parameters
C:\Users\sjmm3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\sjmm3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\inasafe\safe_extras
C:\Users\sjmm3\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by VISCHACA** [comment]
I also feel the same way, has it not been updated and is there a solution of this problem/bug? @timlinux

**Comment by qumleap** [comment]
I have been looking for a solution by other means to no avail. I hope they can come up with something. I will get a hold of a MAC and see if works.

**Comment by VISCHACA** [comment]
Has there been any development/solution yet?

**Comment by elessenger-hit** [comment]
The "imp" module was deprecated in Python 3.11 and removed in Python 3.12. The version of Python shipped with QGIS appears to be 3.12 (at least as of this writing). So, it looks like the module is no longer supported by the current version of QGIS.

The imp module is used in the file `safe/report/impact_report.py`. In researching the issue I found this StackOverflow post with some suggestions: https://stackoverflow.com/questions/69884878/replacing-imp-with-importlib-maintaining-old-behavior. It appears to be a straightforward fix but is nevertheless beyond my ability.
